### ISSUE TITLE
Migrate to Docker Swarm

### ISSUE THREAD

**Issue by andremoreira7** [deviantony/docker-elk#1021]
### Problem description

Hello,
I'm looking forward to use Docker ELK with Swarm mode, in spite of only having 1 node and 1 host available but, for my use case, it makes sense to use Swarm.
The problem I'm currently facing is relative to the setup. I'm not being able to reproduce the needed steps to implement the ELK stack using docker compose, being:
1. " docker compose up setup"
2. " docker compose up -d"

Since the stack only works with the setup command, I really want to know how can I work this around to use it with Docker Swarm.

#### Stack configuration

At first I tried to use a single docker.stack.yml to deploy the stack. However, I realized that it would be impossible due to the fact that the "setup" and "elasticsearch" services need to run first. Which would happen when using docker compose due to the _depends_on_ keyword. So, my solution was to create two separate docker.stack.yml, being:

- docker.stack.setup.yml

```
version: '3.7'

services:

  setup:
    image: docker-elk-setup:8.14.3
    init: true
    volumes:
      - ./setup/entrypoint.sh:/entrypoint.sh:ro,Z
      - ./setup/lib.sh:/lib.sh:ro,Z
      - ./setup/roles:/roles:ro,Z
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
      METRICBEAT_INTERNAL_PASSWORD: ${METRICBEAT_INTERNAL_PASSWORD:-}
      FILEBEAT_INTERNAL_PASSWORD: ${FILEBEAT_INTERNAL_PASSWORD:-}
      HEARTBEAT_INTERNAL_PASSWORD: ${HEARTBEAT_INTERNAL_PASSWORD:-}
      MONITORING_INTERNAL_PASSWORD: ${MONITORING_INTERNAL_PASSWORD:-}
      BEATS_SYSTEM_PASSWORD: ${BEATS_SYSTEM_PASSWORD:-}
    networks:
      - docker-elk
    deploy:
      replicas: 1
      restart_policy:
        condition: none

  elasticsearch:
    image: docker-elk-elasticsearch:8.14.3
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z
      - elasticsearch:/usr/share/elasticsearch/data:Z
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      node.name: elasticsearch
      ES_JAVA_OPTS: -Xms4096m -Xmx4096m
      #ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      discovery.type: single-node
    networks:
      - docker-elk
    deploy:
     mode: replicated
     replicas: 1
     resources:
      limits:
       cpus: '0.25'
       memory: 6144m
     restart_policy:
      condition: on-failure
      
networks:
  docker-elk:
    driver: overlay

volumes:
  elasticsearch:
```

- docker.stack.yml

```
version: '3.7'

services:

  logstash:
    image: docker-elk-logstash:8.14.3
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
    ports:
      - 5044:5044
      - 50000:50000/tcp
      - 50000:50000/udp
      - 9600:9600
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
    networks:
      - docker-elk
    depends_on:
      - elasticsearch
    deploy:
     mode: replicated
     replicas: 1
     resources:
      limits:
       cpus: '0.25'
       memory: 512m
     restart_policy:
      condition: on-failure


  kibana:
    image: docker-elk-kibana:8.14.3
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    ports:
      - 5601:5601
    environment:
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
    networks:
      - docker-elk
    depends_on:
      - elasticsearch
    deploy:
     mode: replicated
     replicas: 1
     resources:
      limits:
       cpus: '0.25'
       memory: 512m
     restart_policy:
      condition: on-failure

  
  curator:
    image: docker-elk-curator:8.14.3
    init: true
    volumes:
      - ./extensions/curator/config/curator.yml:/.curator/curator.yml:ro,Z
      - ./extensions/curator/config/delete_indices.yml:/.curator/delete_indices.yml:ro,Z
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
    networks:
      - docker-elk
    depends_on:
      - elasticsearch
    deploy:
     mode: replicated
     replicas: 1
     resources:
      limits:
       cpus: '0.25'
       memory: 512m
     restart_policy:
      condition: on-failure


  metricbeat:
    image: docker-elk-metricbeat:8.14.3
    # Run as 'root' instead of 'metricbeat' (uid 1000) to allow reading
    # 'docker.sock' and the host's filesystem.
    user: root
    command:
      # Log to stderr.
      - -e
      # Disable config file permissions checks. Allows mounting
      # 'config/metricbeat.yml' even if it's not owned by root.
      # see: https://www.elastic.co/guide/en/beats/libbeat/current/config-file-permissions.html
      - --strict.perms=false
      # Mount point of the host’s filesystem. Required to monitor the host
      # from within a container.
      - --system.hostfs=/hostfs
    volumes:
      - ./extensions/metricbeat/config/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro,Z
      - type: bind
        source: /
        target: /hostfs
        read_only: true
      - type: bind
        source: /sys/fs/cgroup
        target: /hostfs/sys/fs/cgroup
        read_only: true
      - type: bind
        source: /proc
        target: /hostfs/proc
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    environment:
      METRICBEAT_INTERNAL_PASSWORD: ${METRICBEAT_INTERNAL_PASSWORD:-}
      MONITORING_INTERNAL_PASSWORD: ${MONITORING_INTERNAL_PASSWORD:-}
      BEATS_SYSTEM_PASSWORD: ${BEATS_SYSTEM_PASSWORD:-}
    hostname: metricbeat
    networks:
      - docker-elk
    depends_on:
      - elasticsearch
    deploy:
     mode: replicated
     replicas: 1
     resources:
      limits:
       cpus: '0.25'
       memory: 512m
     restart_policy:
      condition: on-failure


  heartbeat:
    image: docker-elk-heartbeat:8.14.3
    command:
      # Log to stderr.
      - -e
      # Disable config file permissions checks. Allows mounting
      # 'config/heartbeat.yml' even if it's not owned by root.
      # see: https://www.elastic.co/guide/en/beats/libbeat/current/config-file-permissions.html
      - --strict.perms=false
    volumes:
      - ./extensions/heartbeat/config/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml:ro,Z
    environment:
      HEARTBEAT_INTERNAL_PASSWORD: ${HEARTBEAT_INTERNAL_PASSWORD:-}
      BEATS_SYSTEM_PASSWORD: ${BEATS_SYSTEM_PASSWORD:-}
    hostname: heartbeat
    networks:
      - docker-elk
    depends_on:
      - elasticsearch
    deploy:
     mode: replicated
     replicas: 1
     resources:
      limits:
       cpus: '0.25'
       memory: 512m
     restart_policy:
      condition: on-failure


  filebeat:
    image: docker-elk-filebeat:8.14.3
    # Run as 'root' instead of 'filebeat' (uid 1000) to allow reading
    # 'docker.sock' and the host's filesystem.
    user: root
    command:
      # Log to stderr.
      - -e
      # Disable config file permissions checks. Allows mounting
      # 'config/filebeat.yml' even if it's not owned by root.
      # see: https://www.elastic.co/guide/en/beats/libbeat/current/config-file-permissions.html
      - --strict.perms=false
    volumes:
      - ./extensions/filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro,Z
      - type: bind
        source: /var/lib/docker/containers
        target: /var/lib/docker/containers
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    environment:
      FILEBEAT_INTERNAL_PASSWORD: ${FILEBEAT_INTERNAL_PASSWORD:-}
      BEATS_SYSTEM_PASSWORD: ${BEATS_SYSTEM_PASSWORD:-}
    hostname: filebeat
    networks:
      - docker-elk
    depends_on:
      - elasticsearch
    deploy:
     mode: replicated
     replicas: 1
     resources:
      limits:
       cpus: '0.25'
       memory: 512m
     restart_policy:
      condition: on-failure


  fleet-server:
    image: docker-elk-fleet-server:8.14.3
    # Run as 'root' instead of 'elastic-agent' (uid 1000) to allow reading
    # 'docker.sock' and the host's filesystem.
    user: root
    volumes:
      - fleet-server:/usr/share/elastic-agent/state:Z
      - type: bind
        source: /var/lib/docker/containers
        target: /var/lib/docker/containers
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    environment:
      FLEET_SERVER_ENABLE: '1'
      FLEET_SERVER_INSECURE_HTTP: '1'
      FLEET_SERVER_HOST: 0.0.0.0
      FLEET_SERVER_POLICY_ID: fleet-server-policy
      # Fleet plugin in Kibana
      KIBANA_FLEET_SETUP: '1'
      # Enrollment.
      # (a) Auto-enroll using basic authentication
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: ${ELASTIC_PASSWORD:-}
      # (b) Enroll using a pre-generated service token
      #FLEET_SERVER_SERVICE_TOKEN: <service_token>
    ports:
      - 8220:8220
    hostname: fleet-server
    # Elastic Agent does not retry failed connections to Kibana upon the initial enrollment phase.
    networks:
      - docker-elk
    depends_on:
      - elasticsearch
      - kibana
    deploy:
     mode: replicated
     replicas: 1
     resources:
      limits:
       cpus: '0.25'
       memory: 512m
     restart_policy:
      condition: on-failure


  apm-server:
    image: docker-elk-apm-server:8.14.3
    volumes:
      - apm-server:/usr/share/elastic-agent/state:Z
    environment:
      FLEET_ENROLL: '1'
      FLEET_TOKEN_POLICY_NAME: Agent Policy APM Server
      FLEET_INSECURE: '1'
      FLEET_URL: http://192.168.1.148:8220
      # Enrollment.
      # (a) Auto-enroll using basic authentication
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: ${ELASTIC_PASSWORD:-}
      # (b) Enroll using a pre-generated enrollment token
      #FLEET_ENROLLMENT_TOKEN: <enrollment_token>
    ports:
      - 8200:8200
    hostname: apm-server
    networks:
      - docker-elk
    depends_on:
      - elasticsearch
      - kibana
      - fleet-server
    deploy:
     mode: replicated
     replicas: 1
     resources:
      limits:
       cpus: '0.25'
       memory: 512m
     restart_policy:
      condition: on-failure

networks:
  docker-elk:
    driver: overlay

volumes:
  elasticsearch:
  fleet-server:
  apm-server:
```

Having these two files, allows me to deploy the setup first and the rest afterwards, which I thought would solve my problem, but it didn't. I'm not sure if this is the way but I'm not being able to work this around.

#### Docker setup

```console
$ docker version

Client: Docker Engine - Community
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:15:16 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:14:12 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

```console
$ docker-compose version

Docker Compose version v2.24.5

```
