### ISSUE TITLE
Docker Log files grow to 5TB weekly in Docker-deployed ELK (Version 7.x) – how to mitigate?

### ISSUE THREAD

**Issue by mengdahuang** [deviantony/docker-elk#1073]
### Problem description

First, many thanks to the team for this project, which allows non-professionals like me to easily run ELK. I have a question:

I’m running ELK (Version 7.x) deployed with Docker, and every week I accumulate about 5TB of log files, as shown in the screenshots below:

<img width="1486" alt="Image" src="https://github.com/user-attachments/assets/f8a18f23-2da7-4fe7-903d-70378bc5db7e" />

<img width="1367" alt="Image" src="https://github.com/user-attachments/assets/db45545b-1ae5-414a-8ffc-1d27bc404dd9" />

As a result, I have to manually use truncate -s 0 every week to clear the logs before restarting the containers.

Most of my logs come from Windows Server sources (AD, Exchange, M365), which are sent to the Logstash container.

Below is my `docker-compose.yml` configuration for reference:

```
cat docker/docker-elk/docker-compose.yml
# version: '3.7'

services:
  setup:
    profiles:
      - setup
    build:
      context: setup/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    init: true
    volumes:
      - ./setup/entrypoint.sh:/entrypoint.sh:ro,Z
      - ./setup/lib.sh:/lib.sh:ro,Z
      - ./setup/roles:/roles:ro,Z
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
      METRICBEAT_INTERNAL_PASSWORD: ${METRICBEAT_INTERNAL_PASSWORD:-}
      FILEBEAT_INTERNAL_PASSWORD: ${FILEBEAT_INTERNAL_PASSWORD:-}
      HEARTBEAT_INTERNAL_PASSWORD: ${HEARTBEAT_INTERNAL_PASSWORD:-}
      MONITORING_INTERNAL_PASSWORD: ${MONITORING_INTERNAL_PASSWORD:-}
      BEATS_SYSTEM_PASSWORD: ${BEATS_SYSTEM_PASSWORD:-}
    networks:
      - elk
    depends_on:
      - elasticsearch

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      node.name: elasticsearch
      ES_JAVA_OPTS: -Xms12g -Xmx12g
      indices.breaker.total.limit: 85%
      # Bootstrap password.
      # Used to initialize the keystore during the initial startup of
      # Elasticsearch. Ignored on subsequent runs.
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/7.17/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elk
    restart: unless-stopped

  logstash:
    image: zl-custom-logstash:latest
    build:
      context: logstash/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/config/log4j2.properties:/usr/share/logstash/config/log4j2.properties
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./data/logstash/data:/usr/share/logstash/data
      - ./data/logstash/logs:/usr/share/logstash/logs
    ports:
      - 5044:5044
      - 58880-58885:58880-58885/tcp
      - 58886:58886/tcp
      - 58887:58887/tcp
      - 58888:58888/tcp
      - 58889:58889/tcp
      - 50000:50000/tcp
      - 50000:50000/udp
      - 9600:9600
    environment:
      LS_JAVA_OPTS: -Xms8g -Xmx8g
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
      LS_OPTS: --config.reload.automatic
    networks:
      - elk
    depends_on:
      - elasticsearch
    restart: unless-stopped

  kibana:
    build:
      context: kibana/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    environment:
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
    networks:
      - elk
    depends_on:
      - elasticsearch
    restart: unless-stopped

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
```
Is there a recommended approach to prevent this issue? Or is there any configuration problem on my end? Any guidance is much appreciated. Thank you!

**Comment by antoineco** [comment]
This problem has more to do with the usage of Logstash than docker-elk's setup, but here are 2 possible tracks I would start exploring:

- Check your Logstash pipeline configuration and make sure that you are not simply logging every message that you receive (e.g. `stdout` output). Debug logging could also generate such amounts of data, if enabled.
- Configure the docker daemon and set limits on the log volume through the [logging driver](https://docs.docker.com/engine/logging/configure/) (see the `json-file` driver). You will need to restart the docker daemon _and_ recreate the containers (`compose down` then `up` again) for the changes to take effect.

**Comment by mengdahuang** [comment]
> 这个问题与 Logstash 的使用有关，而不是 docker-elk 的设置：
> 
> * 检查您的 Logstash 管道配置，确保不是简单地记录收到的每条消息（例如 `stdout` 输出）。如果启用调试日志，也会产生如此大量的数据。
> * 配置 docker 守护进程，并通过日志记录驱动程序（参见 `json-file` 驱动程序）设置日志容量限制。你需要重启 docker 守护进程，并重新创建容器（ `compose down` 然后再 `up` ），才能让更改生效。

Hi, Sir

Indeed, it’s a usage-related issue. Thank you so much for the prompt response and solution. I’ve followed your recommendation to configure the logging driver and set up a scheduled task to perform log rotation.

Additionally, I’d like to ask about the `pipelines.yml` configuration for Logstash. My current configuration looks like this:

```
- pipeline.id: winlogbeat_adfs
  path.config: "/usr/share/logstash/pipeline/winlogbeat-adfs.conf"
  pipeline.workers: 8
  queue.type: persisted
  pipeline.ecs_compatibility: disabled
- pipeline.id: syslog_esg
  path.config: "/usr/share/logstash/pipeline/esgsyslog.conf"
  pipeline.workers: 8
  queue.type: persisted
  pipeline.ecs_compatibility: disabled
- pipeline.id: winlogbeat_laps
  path.config: "/usr/share/logstash/pipeline/winlogbeat-laps.conf"
  pipeline.workers: 2
  queue.type: persisted
  pipeline.ecs_compatibility: disabled
- pipeline.id: winlogbeat_ad
  path.config: "/usr/share/logstash/pipeline/winlogbeat-ad.conf"
  pipeline.workers: 16
  pipeline.batch.size: 5000
  pipeline.batch.delay: 10
  queue.type: persisted
  pipeline.ecs_compatibility: disabled
- pipeline.id: filebeat_o365
  path.config: "/usr/share/logstash/pipeline/filebeat_o365.conf"
  pipeline.workers: 16
  pipeline.batch.size: 5000
  pipeline.batch.delay: 10
  queue.type: persisted
  pipeline.ecs_compatibility: disabled

- pipeline.id: filebeat_ait_qywxapp
  path.config: "/usr/share/logstash/pipeline/filebeat-ait-qywxapp.conf"
  pipeline.workers: 8
  queue.type: persisted
  pipeline.ecs_compatibility: disabled

- pipeline.id: filebeat_bingo
  path.config: "/usr/share/logstash/pipeline/filebeat-bingo.conf"
  pipeline.workers: 8
  queue.type: persisted
  pipeline.ecs_compatibility: disabled
```
Could you please let me know if there are any optimizations I should consider based on this configuration? Thank you!

**Comment by antoineco** [comment]
You shouldn't need to set up a scheduled task. Setting `max-size` and `max-file` in the configuration of the `json-file` driver is enough.

About the pipeline, you need to check each file at `path.config` individually.

**Comment by antoineco** [comment]
I just found out that Compose allows you to set logging options _per service_, which should be even easier to configure that fiddling with the docker daemon: https://docs.docker.com/reference/compose-file/services/#logging

Example:
```yaml
services:

# ...

  logstash:

  # ...

    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: '3'

# ...
```
