### ISSUE TITLE
Xpack Licence has Expired  with Xpack disabled and ELK doens't work anymore

### ISSUE THREAD

**Issue by toni-moreno** [deviantony/docker-elk#154]
After some weeks working with you docker-elk

I've found that today elastic is not working anymore.

````
elasticsearch_1  | [2017-07-28T10:48:23,980][WARN ][o.e.l.LicenseService     ] [ST0JEFS]
elasticsearch_1  | #
elasticsearch_1  | # LICENSE [EXPIRED] ON [FRIDAY, JULY 28, 2017]. IF YOU HAVE A NEW LICENSE, PLEASE UPDATE IT.
elasticsearch_1  | # OTHERWISE, PLEASE REACH OUT TO YOUR SUPPORT CONTACT.
elasticsearch_1  | #
elasticsearch_1  | # COMMERCIAL PLUGINS OPERATING WITH REDUCED FUNCTIONALITY
elasticsearch_1  | # - security
elasticsearch_1  | #  - Cluster health, cluster stats and indices stats operations are blocked
elasticsearch_1  | #  - All data operations (read and write) continue to work
elasticsearch_1  | # - watcher
elasticsearch_1  | #  - PUT / GET watch APIs are disabled, DELETE watch API continues to work
elasticsearch_1  | #  - Watches execute and write to the history
elasticsearch_1  | #  - The actions of the watches don't execute
elasticsearch_1  | # - monitoring
elasticsearch_1  | #  - The agent will stop collecting cluster and indices metrics
elasticsearch_1  | #  - The agent will stop automatically cleaning indices older than [xpack.monitoring.history.duration]
elasticsearch_1  | # - graph
elasticsearch_1  | #  - Graph explore APIs are disabled
elasticsearch_1  | # - ml
elasticsearch_1  | #  - Machine learning APIs are disabled
````
But I've the following elasticsearch elasticsearch.yml

````
---
## Default Elasticsearch configuration from elasticsearch-docker.
## from https://github.com/elastic/elasticsearch-docker/blob/master/build/elasticsearch/elasticsearch.yml
#
cluster.name: "docker-cluster"
network.host: 0.0.0.0

# minimum_master_nodes need to be explicitly set when bound on a public IP
# set to 1 to allow single node clusters
# Details: https://github.com/elastic/elasticsearch/pull/17288
discovery.zen.minimum_master_nodes: 1

## Use single node discovery in order to disable production mode and avoid bootstrap checks
## see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
#
discovery.type: single-node

## Disable X-Pack
## see https://www.elastic.co/guide/en/x-pack/current/xpack-settings.html
##     https://www.elastic.co/guide/en/x-pack/current/installing-xpack.html#xpack-enabling
#
xpack.security.enabled: false
xpack.monitoring.enabled: false
xpack.ml.enabled: false
xpack.graph.enabled: false
xpack.watcher.enabled: false
````

**Comment by antoineco** [comment]
This is only a warning, X-Pack plugins will operate with reduced functionality but both ES and Kibana will keep running as usual. The message is safe to ignore since you don't use X-Pack functionalities as you pointed out.

Send ES the following request to confirm all plugins are disabled:

```console
$ curl http://localhost:9200/_xpack/?pretty=true

```json
...
        "monitoring": {
            "available": true,
            "description": "Monitoring for the Elastic Stack",
            "enabled": false
        },
        "security": {
            "available": true,
            "description": "Security for the Elastic Stack",
            "enabled": false
        },
...
```

**Comment by toni-moreno** [comment]
This is my output, what to do now?, my ELK is still failing!!

````
# curl http://localhost:9200/_xpack/?pretty=true
{
  "build" : {
    "hash" : "88a84cf",
    "date" : "2017-06-30T23:36:07.678Z"
  },
  "license" : {
    "uid" : "d9c9f262-3cc5-4f3d-aa75-13dfd53f5738",
    "type" : "trial",
    "mode" : "trial",
    "status" : "expired",
    "expiry_date_in_millis" : 1501237103978
  },
  "features" : {
    "graph" : {
      "description" : "Graph Data Exploration for the Elastic Stack",
      "available" : true,
      "enabled" : false
    },
    "ml" : {
      "description" : "Machine Learning for the Elastic Stack",
      "available" : true,
      "enabled" : false,
      "native_code_info" : {
        "version" : "N/A",
        "build_hash" : "N/A"
      }
    },
    "monitoring" : {
      "description" : "Monitoring for the Elastic Stack",
      "available" : true,
      "enabled" : false
    },
    "security" : {
      "description" : "Security for the Elastic Stack",
      "available" : true,
      "enabled" : false
    },
    "watcher" : {
      "description" : "Alerting, Notification and Automation for the Elastic Stack",
      "available" : true,
      "enabled" : false
    }
  },
  "tagline" : "You know, for X"
}
````

**Comment by antoineco** [comment]
What do you mean failing? Does it reject input?

**Comment by antoineco** [comment]
ping @toni-moreno. Could you please describe how ES is failing in case this issue is still valid?

Repeating myself to make it clear: the message you're seeing is a **WARN**, not an ERROR, so I'm quite certain ES is running just fine. If you can live with seeing this warning on every startup just let it be.

Otherwise:

1. add `RUN elasticsearch-plugin remove x-pack` at the end of your ES Dockerfile
2. remove all `xpack.*` options from your `elasticsearch.yml` file
3. recreate the `elasticsearch` image + container
      ```console
      $ docker-compose build elasticsearch
      Building elasticsearch
      ...
      Successfully tagged dockerelk_elasticsearch:latest

      $ docker-compose up -d elasticsearch
      Recreating dockerelk_elasticsearch_1 ... 
      Recreating dockerelk_elasticsearch_1 ... done
      ```
4. repeat the operation with `kibana`

**Comment by toni-moreno** [comment]
Sorry @antoineco I will be out of office for some days I'll test these 4 steps ASAP.  Thank you very much.

**Comment by toni-moreno** [comment]
Hi again @antoineco.

When trying to build  I can not rebuild now the new image because it takes all volume data  "./elasticsearch/data" and "./elasticsearch/logs" contained in the volumes into the image and  ,  and I don't want to store this data into image (near 200Gb of data). The only way to avoid this is use "image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0" instead of "build: elasticsearch/"

This is my custom docker-compose.yml. There is any easy way to build directly from the docker-compose and avoid volume data inclusion? 

````yaml
services:
  elasticsearch:
    restart: always
    #image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
    build: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=loweb-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xmx2048m -Xms2048m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      mem_limit: 1g
    networks:
      - elk
````
