### ISSUE TITLE
Consider adding security tips to README.md?

### ISSUE THREAD

**Issue by serain** [deviantony/docker-elk#163]
By default this build is quite insecure. Kibana and Elasticsearch are wide open and not everyone wants to pay for XPack. 

In my case I've slapped on `nginx-proxy` (https://github.com/jwilder/nginx-proxy) to put Kibana behind an SSL proxy with Basic Auth and configured to not expose Elastic and Kibana directly.

Would maybe be worth pointing out the security risks of the default build and giving some tips on hardening?

```
version: '2'

services:

  elasticsearch:
    build: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200
      - 9300
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    build: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - 5601
    networks:
      - elk
    environment:
      - VIRTUAL_HOST=dev.host.local
    depends_on:
      - elasticsearch

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "443:443"
    networks:
      - elk
    volumes:
      - ./kibana/config/certs/:/etc/nginx/certs:ro
      - ./kibana/config/htpasswd:/etc/nginx/htpasswd:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

networks:

  elk:
    driver: bridge
```

**Comment by floragunncom** [comment]
Why not Search Guard? Community edition is free and open source. 
See  https://github.com/deviantony/docker-elk/tree/searchguard and https://floragunn.com/elasticsearch-proxy-security/

**Comment by antoineco** [comment]
It's good to suggest additions like this that can be added to the wiki, or as an extension where it makes sense.

I would just like to comment on this:

> not everyone wants to pay for XPack.

X-Pack is disabled on the master branch. The demo license will expire after 30 days, but the warning can be safely ignored since all X-Pack features are explicitly turned off.

**Comment by deviantony** [comment]
I agree with @antoineco and would rather see these kind of suggestions added as a Wiki entry (because this is not really an extension).

**Comment by ckuethe** [comment]
X-Pack is being open-sourced...

https://www.elastic.co/products/x-pack/open

**Comment by kusmierz** [comment]
As far as I can see, free `x-pack` has no security option at all (user management/auth), see https://www.elastic.co/subscriptions.

The question is, is it possible to mix free `x-pack`'s features with `Search Guard` security?

**Comment by dhabierre** [comment]
What about Trafik?
You can set-up basic authentification over HTTPS (using Let's Encrypt / labels).

```
version: '2.4' # last version that supports depends_on / condition...

services:

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    ports:
      - 9200 # not expose publicly
      - 9300 # not expose publicly
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - elk
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=elk"
      - "traefik.backend=elasticsearch"
      - "traefik.frontend.rule=Host:elasticsearch.YOUR_DOMAIN.org"
      - "traefik.frontend.auth.basic=admin:$$apr1$$03ie1mln$$PZOTjSLEIUkzrflx9UHQL0"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.port=9200"
    healthcheck:
      test: curl -f http://elasticsearch:9200 || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
    restart: always

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    ports:
      - 5601 # not expose publicly
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
      - kibana_data:/usr/share/kibana/data
    networks:
      - elk
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=elk"
      - "traefik.backend=kibana"
      - "traefik.frontend.rule=Host:kibana.YOUR_DOMAIN.org"
      - "traefik.frontend.auth.basic=admin:$$apr1$$xzy62amt$$hhFJuZ3TpL8nu1BfzJL2z0"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.port=5601"
    healthcheck:
      test: curl -f http://kibana:5601 || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: always

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    ports:
      - 5000:5000
      - 5010:5010
      - 9600:9600
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./logstash/templates:/usr/share/logstash/templates:ro
    networks:
      - elk
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: always

  traefik:
    build:
      context: traefik/
      args:
        TRAEFIK_VERSION: $TRAEFIK_VERSION
    command: --api --docker # Enables the web UI (local port 8080) and tells Traefik to listen to docker
    ports:
      - 443:443
    expose:
      - 8080 # not expose publicly
    volumes:
      - ./traefik/config/traefik.toml:/traefik.toml
      - ./traefik/config/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - elk
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:traefik.YOUR_DOMAIN.org"
      - "traefik.frontend.auth.basic=admin:$$apr1$$zdmn7fjs$$zuJdq6w.PhQ9r1FttqfvX1"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.port=8080"
    # to avoid 502 (in monitoring / health) while services are not ready
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
    restart: always

# volumes are located to /var/lib/docker/volumes/ (on host)
volumes:
  elasticsearch_data:
    driver: local
  kibana_data:
    driver: local

networks:
  elk:
    driver: bridge
```
