### ISSUE TITLE
problem adding ssl keys for beat plugin

### ISSUE THREAD

**Issue by leberkas** [deviantony/docker-elk#171]
I try to add ssl cert and key for the beats plugin. i created a folder under logstash and mount this folder in the docker-compose.yml:

```
 logstash:
    build: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/certs:/certs
    ports:
      - "5544:5544"
      - "32101:32101"
      - "32102:32102"
``` 

when i start the container, i always get this:
```
logstash_1       |   input {
logstash_1       |     beats {
logstash_1       |       # This setting must be a path
logstash_1       |       # File does not exist or cannot be opened /certs/lsf.crt
logstash_1       |       ssl_certificate => "/certs/lsf.crt"
logstash_1       |       ...
logstash_1       |     }
```

i also tried to add the files to the image, which results in the same error message.

configfile:
```
input {
  tcp {
    port => 5000
  }
  beats {
    port => 32102
    ssl => true
    ssl_certificate => "/certs/lsf.crt"
    ssl_key => "/certs/lsf.key"
  }
}
...
```
