### ISSUE TITLE
pipeline doesn't live long

### ISSUE THREAD

**Issue by shangwenqingqing** [deviantony/docker-elk#195]
logstash_1       | 02:26:01.372 [LogStash::Runner] WARN  logstash.agent - stopping pipeline {:id=>"main"}
dockerelk_logstash_1 exited with code 0

**Comment by simon-tannai** [comment]
Same error :(

**Comment by antoineco** [comment]
You'll have to be a little bit more specific if you want some help guys.

**Comment by simon-tannai** [comment]
My docker-compose:
```
  logstash:
    build:
      context: ./elk/logstash
      dockerfile: Dockerfile.dev
    volumes:
      - ./elk/logstash/config/:/usr/share/logstash/config/
      - ./elk/logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    networks:
      test_network:
        ipv4_address: 172.10.10.103
```

logstash.conf:
```
input {
	tcp {
		port => 9900
	}
}

output {
  stdout { debug => true }
}

filter {
  json {
    source => "message"
  }
}
```

Docker logs:
```
19:26:39.475 [[main]-pipeline-manager] INFO  logstash.pipeline - Pipeline main started
19:26:39.523 [Api Webserver] INFO  logstash.agent - Successfully started Logstash API endpoint {:port=>9600}
19:26:42.489 [LogStash::Runner] WARN  logstash.agent - stopping pipeline {:id=>"main"}
```
