### ISSUE TITLE
x-pack branch - password changes

### ISSUE THREAD

**Issue by liamptk** [deviantony/docker-elk#211]
docker-compose.yml
```
version: '2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/data/:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: "NewPassword"
    networks:
      - elk

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
    ports:
      - "5000:5000"
      - "5044:5044"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      xpack.monitoring.elasticsearch.password: "NewPassword"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml

networks:
  elk:
    driver: bridge
```

Kibana.yml
```
server.name: kibana
server.host: "0"
elasticsearch.url: http://elasticsearch:9200
elasticsearch.password: NewPassword
```

Logstash.yml
```
http.host: 0.0.0.0
path.config: /usr/share/logstash/pipeline
xpack.monitoring.elasticsearch.password: NewPassword
```

I've tried an assortment of different things to get this working. One approach that had the setup working was to change the elasticsearch.username in the Logstash.yml file to 'elastic' which overides the 'logstash_system' user. The problem with this was when a password is entered incorrectly the whole system locks out.

I've tried using the `bin/x-pack/setup-passwords interactive` command and configuring the passwords this way too, this also failed.

The branch is also missing default logstash / kibana yaml files, is this standard? I copied the default layouts from the Master branch.

Error
```
logstash_1       | [2017-12-12T16:50:00,769][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http://logstash_system:xxxxxx@localhost:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://logstash_system:xxxxxx@localhost:9200/][Manticore::SocketException] Connection refused (Connection refused)"}
```

**Comment by antoineco** [comment]
Adding the links I referenced in another issue for reference:

X-Pack for the Elastic Stack [6.0] » Securing Elasticsearch and Kibana »
 * [Getting Started with Security](https://www.elastic.co/guide/en/x-pack/6.0/security-getting-started.html)
 * [Setting Up User Authentication](https://www.elastic.co/guide/en/x-pack/current/setting-up-authentication.html#set-built-in-user-passwords)

**Comment by liamptk** [comment]
@antoineco 

I've been through that approach and configured the passwords with x-pack along with updating the passwords in the yaml files (see above). Still no joy.

**Comment by antoineco** [comment]
Here's what I did:

1. **Generate new passwords for built-in users**

```console
# docker-compose exec elasticsearch bin/x-pack/setup-passwords auto

Initiating the setup of reserved user elastic,kibana,logstash_system passwords.
The passwords will be randomly generated and printed to the console.
Please confirm that you would like to continue [y/N]y


Changed password for user kibana
PASSWORD kibana = $fREKVMGQyG19oX%~fs@

Changed password for user logstash_system
PASSWORD logstash_system = rjUK$+&kEC?#0L8mY%np

Changed password for user elastic
PASSWORD elastic = mc~?DPIUhj-!kUMr+~dd
```

2. **Create/Update configs (see README)**

[`logstash.yml`](https://github.com/elastic/logstash-docker/blob/master/build/logstash/config/logstash-x-pack.yml#L5) / [`kibana.yml`](https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana-x-pack.yml#L8)

eg.

```yml
# config/logstash.yml
xpack.monitoring.elasticsearch.username: logstash_system
xpack.monitoring.elasticsearch.password: 'rjUK$+&kEC?#0L8mY%np'
```

```yml
# config/kibana.yml
elasticsearch.username: kibana
elasticsearch.password: '$fREKVMGQyG19oX%~fs@'
```

```
# pipeline/logstash.conf
...
		user => elastic
		password => 'mc~?DPIUhj-!kUMr+~dd'
```

3. **Restart the stack**

```console
# docker-compose restart
```

So far so good, I can login to Kibana and ship logs via Logstash.
Can you try on your side?
