### ISSUE TITLE
Error during index pattern creation via web UI

### ISSUE THREAD

**Issue by antoineco** [deviantony/docker-elk#221]
Since v6.1.0 it seems impossible to create a Kibana index pattern on the `searchguard` branch. The `kibanaserver` user doesn't have enough permissions:

`[security_exception] no permissions for [indices:data/read/field_caps] and User [name=kibanaserver, roles=[], requestedTenant=null]`

ping @floragunncom @jochenkressin, care to take a look?

**Comment by floragunncom** [comment]
I guess you need to copy over the default config files from https://github.com/floragunncom/search-guard/tree/es-6.1.1/sgconfig to docker-elk/elasticsearch/config/sg/ because they changed a little bit for 6.x.

**Comment by antoineco** [comment]
Yes I've done that in my last commit, `admin` works but not `kibanaserver`.
It's not a big annoyance of course, but I was wondering if you were aware of it.

**Comment by jochenkressin** [comment]
This may be a dumb question, but could it be that you use the kibanaserver user to log in to Kibana? This user is for Kibana internal use only, a regular user needs to have the sg_kibana_user role, which has the field_caps permission set already:

```
sg_kibana_user:
  readonly: true
  cluster:
    - MONITOR
    - CLUSTER_COMPOSITE_OPS_RO
  indices:
    '?kibana':
      '*':
        - MANAGE
        - INDEX
        - READ
        - DELETE
    '*':
      '*':
        - indices:data/read/field_caps
```

In addition, the Kibana user needs to have at least READ access to the indices he/she wants to access with Kibana.

In the demo files this would be the `kibanaro` user, which is assigned to the sg_kibana_user and the sg_readall role.
