### ISSUE TITLE
Connection reset using http plugin

### ISSUE THREAD

**Issue by Redsandro** [deviantony/docker-elk#236]
Simply adding the http plugin to the logstash pipeline does not work as expected.

```
input {
	http {
		port => 12203
		type => "test"
	}
}
```

I'm getting _"The connection was reset"._ Not refused, but reset. So something is working. But I'm kind of waiting to see the magic letters _"ok"_ in a response.

Needless to say, I did add the port to the ` elasticsearch` portion of the compose file:

```
  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - 9200:9200
      - 9300:9300
      - 12203:12203
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
```
