### ISSUE TITLE
Logstash Input http is not coming up

### ISSUE THREAD

**Issue by Huppys** [deviantony/docker-elk#237]
Hi,

I've configured logstash to initialize the plugin `input http`.

````
input {
	http {
		host => "0.0.0.0"
		port => 4999
		codec => "json"
		response_headers => {
			"Access-Control-Allow-Origin" => "*"
			"Content-Type" => "application/json"
			"Access-Control-Allow-Headers" => "Origin, X-Requested-With, Content-Type, Accept"
		}
	}
}
````

I updated `docker-compose.yml`, too.
````
logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline/:/usr/share/logstash/pipeline:ro
    ports:
      - "4999:4999"
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch
````

After I've edited these files, I ran `docker-compose build` followed by `docker-compose up`.

The output shows me the `tcp input` gets initialized:
````
"logEvent":{"message":"Starting tcp input listener","address":"0.0.0.0:5000","ssl_enable":"false"}}
````

But no log about the `http input`. 

Could anybody help, please?

Best,
Oli
