### ISSUE TITLE
Search Guard Kibana GUI not showing

### ISSUE THREAD

**Issue by plambhsa** [deviantony/docker-elk#242]
I believe that logging in with the default admin user should give the Search Guard menu item in the left hand menu. However, it doesn't show up. is there some other configuration that needs to be done to make that menu option appear and usable?

**Comment by plambhsa** [comment]
I have tried the steps in that issue. 

```
# sg_roles.yml
sg_all_access:
#   readonly: true
  cluster:
    - UNLIMITED
  indices:
    '*':
      '*':
        - UNLIMITED
  tenants:
    admin_tenant: RW
```

```
# sg_internal_users.yml
admin:
#   readonly: true
  hash: $2a$12$VcCDgh2NDk07JGN0rjGbM.Ad41qVR/YFJcgHp0UGns5JDymv..TOG
  roles:
    - admin
    - sg_all_access
```

```
# elasticsearch.yml
searchguard.restapi.roles_enabled: ["sg_all_access"]
```

I tried each of those changes, and after each change I'd run `docker-compose build`, then `docker-compose up`. Still haven't been able to get the menu item to show up.
