### ISSUE TITLE
memory locking requested for elasticsearch process but memory is not locked

### ISSUE THREAD

**Issue by RANGERBEE** [deviantony/docker-elk#243]
Hello guys!

  My Host is Centos7. All components fully updated. I have commented out the single-node parameter in the elasticsearch.yml file. I am trying to cluster to an external host.  My .yml file is as follows:

```yml
## Default Elasticsearch configuration from elasticsearch-docker.
## from https://github.com/elastic/elasticsearch-docker/blob/master/build/elasticsearch/elasticsearch.yml
#
cluster.name: "docker-cluster"
network.host: 0.0.0.0
network.publish_host: 10.0.1.194
node.master: true
node.data: true
bootstrap.memory_lock: true
#discovery.type: single-node
```
In /etc/security/limits.conf I have set:

```yml
elasticsearch - nofile 65535
elasticsearch - memlock unlimited
root - memlock unlimited
elasticsearch soft memlock unlimited
elasticsearch hard memlock unlimited
docker - nofile 65535
docker - memlock unlimited
docker soft memlock unlimited
docker hard memlock unlimited
user hard memlock unlimited
user soft memlock unlimited
user - memlock unlimited
```
also set --

```console
sysctl -w vm.swappiness=1;
sysctl -w vm.max_map_count=262144;
```
Any ideas why when trying to start the stack with "docker-compose up", I get elasticsearch failing with error - "memory locking requested for elasticsearch process but memory is not locked"
```console
2/6/2018 11:16:58 PM	# allow user 'elasticsearch' mlockall
2/6/2018 11:16:58 PM	elasticsearch soft memlock unlimited
2/6/2018 11:16:58 PM	elasticsearch hard memlock unlimited
```

Thanks!!

**Comment by antoineco** [comment]
You also have to set the `ulimits` settings properly on the container itself, and probably (can't remember for sure) run it with extra privileges.

Please note that setting user specific limits on the host is irrelevant here.

I've seen that before myself:

https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html

https://github.com/pires/docker-elasticsearch/issues/7

**Comment by RANGERBEE** [comment]
Thank you!!  Wow, thats a good find....    testing this today.

**Comment by RANGERBEE** [comment]
Added the following and works perfectly!  Thank you...

```yml
version: '2'

services:

  elasticsearch:
    restart: always
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx2048m -Xms2048m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
```
