### ISSUE TITLE
Elasticsearch-Cluster - multiple docker hosts

### ISSUE THREAD

**Issue by NiTRoeSE** [deviantony/docker-elk#247]
Hi everyone, because of failover and capacity problems i want to extend our running docker-elk stack with other elasticsearch containers running at other docker hosts to build finally a cluster. 

I have tryed various ways to connect the other elasticsearch-containers to the docker-elk elasticsearch and get everytime the same failure.

To achieve this i have modified the docker-compose.yml

```
elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticdata:/usr/share/elasticsearch/data:rw
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "ES_JAVA_OPTS: -Xmx512m -Xms512m"
      - "node.master=true"
      - "node.data=true"
      - "discovery.type=zen"
      - "discovery.zen.ping.unicast.hosts=10.1.148.105"
      - "discovery.zen.minimum_master_nodes: 2"
      - "network.publish_host: 10.1.148.101"
   #   - "network.host: 10.1.148.101"
      - "transport.tcp.port: 9300"
      - "transport.publish_port: 9300"
      - "transport.publish_host: 10.1.146.101"
    networks:
      - elk


```
The problem is wether i set environment variables like "network.publish_host" or not the docker-elk elasticsearch-container is not able to get a connection to the other elasticsearch-containers located on other docker hosts.

The "first contact" seems to be established but any other step fails because the docker-elk elasticsearch container sends false data (ip) :

```

[2018-02-21T09:00:05,452][INFO ][o.e.d.z.ZenDiscovery     ] [le5dh03] failed to send join request to master [{docker16_elasticsearch}{SDzZB1bsTg2bIdV-WOO5lQ}{AZP9cqBvTu-R4z_XM5tjVQ}{10.1.148.105}{10.1.148.105:9300}], reason [RemoteTransportException[[docker16_elasticsearch][172.24.0.2:9300][internal:discovery/zen/join]]; nested: ConnectTransportException[[le5dh03][172.18.0.2:9300] connect_timeout[30s]]; ]

```

I need help to get this running.. I don´t know how i can this achieve..
In my opinion it should work so, but maybe i dont see something important or so ?

thanks in advanced 

( How is the recommended way to get docker-elk stack running with elasticdearch-cluster wich containers are hosted on multiple docker hosts and not at the same docker host ? (Wiki only shows a way how to get running a elasticsearch-cluster on the same host))
