### ISSUE TITLE
Input file in logstash

### ISSUE THREAD

**Issue by disastrous-charly** [deviantony/docker-elk#25]
Hello, 

I'm trying to use your project with a input of type "file" in logstash, instead of sending them with TCP.
I mount my log folder on my logstash container, I can see them in the container, no problem.

But in Kibana, I can't create an index, so I guess logstash don't push my log files to elastic.
Do you know if it comes from your configuration ?

Your work is really awesome BTW !

**Comment by deviantony** [comment]
I've just tried it on my workstation at work but I'm having troubles inspecting docker containers using `docker exec` (I can't see the mounted logstash configuration nor the mounted log files)

I'll try again on my personal laptop.

**Comment by deviantony** [comment]
I made it ! 

In order to use the file input in logstash, you'll have to update the *start_position* option.

The default value is "end" which means the logstash container will only tail the new lines in the log file, see https://www.elastic.co/guide/en/logstash/current/plugins-inputs-file.html#plugins-inputs-file-start_position

I've used the following container definition for logstash:

```yml
logstash:
  image: logstash:latest
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
    - /tmp/logstash/:/logstash
  ports:
    - "5000:5000"
  links:
    - elasticsearch
```

And the following logstash configuration:

```
input {
	file {
		path => "/logstash/test.log"
		start_position => "beginning"
	}
}

output {
	elasticsearch {
		hosts => "elasticsearch:9200"
	}
}
```

With a log file `/tmp/logstash/test.log`, works perfectly !
