### ISSUE TITLE
In docker-compose.yml command line is not working

### ISSUE THREAD

**Issue by veeruborra** [deviantony/docker-elk#30]
The command line (logstash -f /etc/logstash/conf.d/logstash.conf) in docker-compose.yml is not responding..
After the docker-elk started(docker-compose up) we must go to logstash container and we must execute the command (logstash -f  /etc/logstash/conf.d/logstash.conf ) or (logstash agent -f /etc/logstash/conf.d/logstash.conf -w 10 &).. Then only my logs are showing in kibana

**Comment by deviantony** [comment]
Well weird, do you got any logstash logs? On the filesystem or in the docker-compose output?

**Comment by veeruborra** [comment]
yep i got the logs in logstash.
when i run docker-compose up,the containers starts and then i must go to logstash container by typing
->docker exec -it (conatineridor name) bin/bash
it will move to logstash and then
-> ogstash agent -f /etc/logstash/conf.d/logstash.conf -w 10 &
then only my logs are showing in http:9200

**Comment by deviantony** [comment]
Nope, I was speaking about logstash process logs.

Could you update the logstash container definition in docker-compose.yml to:

```yml
logstash:
  image: logstash:latest
  command: logstash -f /etc/logstash/conf.d/logstash.conf -l /var/log/logstash/logstash.log --debug
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
  ports:
    - "5000:5000"
  links:
    - elasticsearch
```

Then, start the stack and use `docker exec` to log in the container and have a look at the file */var/log/logstash/logstash.log*.
