### ISSUE TITLE
Filebeat cannot resolve Logstash IP in docker stack

### ISSUE THREAD

**Issue by unixslayer** [deviantony/docker-elk#340]
### Problem description

Filebeat cannot resolve Logstash IP in docker stack by service name. All other services can connect to each other. For example PHP can connect to ES by "elasticsearch:9200" configuration.

#### Stack configuration
*docker-compose.yml*
```yaml
  logstash:
    container_name: logstash
    build: ./docker/logstash
    networks:
      - elk
    ports:
      - "5044:5044"
    volumes:
      - ./docker/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./docker/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"

  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:5.6.14
    restart: "no"
    command: "filebeat -e -d *"
    networks:
      - elk
    depends_on:
      - logstash
      - elasticsearch
      - kibana
    volumes:
      - ./docker/filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./var/log:/var/log/magento:ro
```
*Logstash Dockerfile*
```
FROM docker.elastic.co/logstash/logstash:5.6.14

RUN bin/logstash-plugin install logstash-input-beats
```
*logstash.conf*
```conf
input {
	beats {
	    port => 5044
	    host => "0.0.0.0"
    }
}

output {
    elasticsearch {
        hosts => "elasticsearch:9200"
        index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
        document_type => "%{[@metadata][type]}"
    }
}
```
*filebeat.yml*
```yaml
setup.kibana:
  host: "kibana:5601"

filebeat:
  prospectors:
    - input_type: log
      paths:
        - /var/log/magento/*.log

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
```

#### Docker setup
Docker version 18.09.0, build 4d60db4
docker-compose version 1.23.1, build b02f1306
docker-compose.yml version 2.3

#### Docker logs
Following messages are logged by filebeat:
```log
filebeat          | 2018/12/14 07:52:51.074244 sync.go:58: DBG  connect to logstash host logstash:5044:10200
filebeat          | 2018/12/14 07:52:51.076637 single.go:140: ERR Connecting error publishing events (retrying): dial tcp 130.255.154.100:5044: getsockopt: connection refused
```
I'm confused with `logstash:5044:10200`. When using logstash container physical address, eg. 172.31.0.2, everything is fine. Unfortunately using static IP is not an option. I don't think that this is a Docker issue, because other services connects to each other the same way correctly.

**Comment by antoineco** [comment]
Did you forget to set the network name?
```
    networks:
      - elk
```
(see unmodified compose file)

**Comment by antoineco** [comment]
The fact that this name resolves to `130.255.154.100:5044` makes me believe something's wrong with the local Docker DNS, but then the error should also occur with Logstash and Kibana.

Can you reproduce this consistently?

**Comment by antoineco** [comment]
Could you also try setting the port number independently from the host name?

https://www.elastic.co/guide/en/beats/filebeat/5.3/logstash-output.html#port

**Comment by unixslayer** [comment]
We can reproduce it with the same result every time no matter what machine this configuration is run on.
I've changed filebeat configuration as follow:
```yaml
setup.kibana:
  host: "kibana:5601"

filebeat:
  prospectors:
    - input_type: log
      paths:
        - /var/log/magento/*.log

output.logstash:
  hosts: ["logstash"]
  port: 5044

logging.level: info
```
now filebeat logs this:
```log
filebeat          | 2018/12/14 10:39:23.750165 sync.go:58: DBG  connect to logstash host logstash:5044
filebeat          | 2018/12/14 10:39:23.752184 single.go:140: ERR Connecting error publishing events (retrying): dial tcp 130.255.154.100:5044: getsockopt: connection refused
```
Looks like docker issue, but other servises talks to each other correctly.
