### ISSUE TITLE
logstash container exit a liitle after start

### ISSUE THREAD

**Issue by wanghaisheng** [deviantony/docker-elk#35]
yml
```
elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"
logstash:
  image: logstash:latest
  command: logstash -f /etc/logstash/conf.d/multilinejson.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
    - ./logstash/data:/logstash
  ports:
    - "5000:5000"
  links:
    - elasticsearch
kibana:
  build: kibana/
  volumes:
    - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
  ports:
    - "5601:5601"
  links:
    - elasticsearch

```
multilinejson  config
```
input 
{   
    file 
    {
        codec => multiline
        {
            pattern => '^\{'
            negate => true
            what => previous                
        }
        path => ["/logstash/test01.json"]
        start_position => "beginning"
        sincedb_path => "/dev/null"
        exclude => "*.gz"
    }
}

filter 
{
    mutate
    {
        replace => [ "message", "%{message}}" ]
        gsub => [ 'message','\n','']
    }
    if [message] =~ /^{.*}$/ 
    {
        json { source => message }
    }

}

output
{ 
  elasticsearch {
    protocol => "http"
    codec => json
    hosts => "elasticsearch:9200"
    index => "json"
    embedded => true
  }

    stdout { codec => rubydebug }

```

test01.json
```
{
    "SOURCE":"Source A",
    "Model":"ModelABC",
    "Qty":"3"
}
```
