### ISSUE TITLE
Missing needed index fields.

### ISSUE THREAD

**Issue by rong0312** [deviantony/docker-elk#352]
### Problem description

Missing needed fields, resulting with dashboard errors and efficient logging.

### Extra information
Comparings docker swarm ELK vs normal hosted ELK.

**Client side:**
I am Using the same host & metricbeat configuration to send data to  deviantony/docker-elk docker stack (missing fields) and to another plain vanilla ELK which is host based for comparison.
Compose file is attached bellow,

In this issue i will refer to "Metricbeat" for mongodb but other beats didn't
fulfil other dashboards as well.

#### Stack configuration

docker-compose.yml:

```
version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx1500m -Xms1500m"
      cluster.name: "elk-cluster"
      network.host: 0.0.0.0
      discovery.zen.ping.unicast.hosts: tasks.elasticsearch
      discovery.type: zen
      discovery.zen.minimum_master_nodes: 2
      xpack.monitoring.enabled: "true"
      xpack.monitoring.collection.enabled: "true"
    networks:
      - elk
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

  logstash:
    image: docker.elastic.co/logstash/logstash:6.5.4
    ports:
      - "5000:5000"
      - "5044:5044"
      - "9600:9600"
    configs:
      - source: logstash_pipeline
        target: /usr/share/logstash/pipeline/logstash.conf
    environment:
      LS_JAVA_OPTS: "-Xmx500m -Xms500m"
      http.host: "0.0.0.0"
      xpack.monitoring.elasticsearch.url: http://elasticsearch:9200
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.4
    ports:
      - "5601:5601"
    environment:
      server.name: kibana
      server.host: "0"
      elasticsearch.url: http://elasticsearch:9200
      xpack.monitoring.ui.container.elasticsearch.enabled: "true"
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

configs:
  logstash_pipeline:
    file: ./logstash/pipeline/logstash.conf

networks:
  elk:
    driver: overlay
```

------------------------END OF COMPOSE --------------------------

### Additional information and pics:

Both cases came from same metricbeat configuration and host as mentioned.
Difference between docker stack and plain host ELK:

#### Docker stack fields:
![screen shot 2019-01-17 at 9 12 52](https://user-images.githubusercontent.com/33253167/51305717-52289380-1a44-11e9-9280-9ce6fcb9d709.png)

#### Plain host fields:
![screen shot 2019-01-17 at 9 13 09](https://user-images.githubusercontent.com/33253167/51305780-78e6ca00-1a44-11e9-9f5f-19ae9e9b956e.png)

Please notice the fields! any idea why there is such gap? 
did anyone else faced issues related to uploaded dashboards from beats?
missing fields?

even when i query kibana:   GET metricbeat-6.5.4-2019.01.17/_mapping
I see huge difference between the solutions (10x more lines in plain hosted ELK).

Any guidance will be welcome and appreciated.
Thanks alot!
Ron

#### Dashboard:

![screen shot 2019-01-17 at 10 39 06](https://user-images.githubusercontent.com/33253167/51306078-2823a100-1a45-11e9-97e4-cb2c7db7815e.png)
