### ISSUE TITLE
Setting log level to debug for one fo the apps

### ISSUE THREAD

**Issue by beechovsky** [deviantony/docker-elk#356]
Hi, I'd like to set the log level to debug for Logstash (or any app, really), but passing the argument in the right place is confusing. I feel like I need to pass it in the docker-compose.yml file using ```command: --log.level debug```, but that requires messing with the endpoint apparently.

**Comment by antoineco** [comment]
Does this answer your question by any chance?

https://github.com/deviantony/docker-elk/blob/master/README.md#how-can-i-tune-the-elasticsearch-configuration

**Comment by beechovsky** [comment]
Hi! Actually just adding the line ```command: --log.level debug``` to the docker-compose.yml file worked on a second attempt. I must have done something else that broke it. Thanks!

**Comment by beechovsky** [comment]
For posterity's sake, here's how to do it:
```
logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    ...
    command: --log.level debug
```
