### ISSUE TITLE
config.reload configuration for logstash

### ISSUE THREAD

**Issue by rong0312** [deviantony/docker-elk#357]
### Problem description

Cant make my logstash to auto reload changed configuration.

### Extra information

I have tried to add reload command to my compose file but failed to do so.

#### Compose setup
So this is my Logstash section:

```
logstash:
    image: docker.elastic.co/logstash/logstash:6.5.4
    command: bin/logstash –f apache.config --config.reload.automatic --config.reload.interval 10
    ports:
      - "5000:5000"
      - "5044:5044"
      - "9600:9600"
.
.
.
```

#### Docker logs
Logstash service logs:

```
elk_logstash.1.ek1c7vid194o@ELK2-DEV    | ERROR: Unknown command '–f'
elk_logstash.1.ek1c7vid194o@ELK2-DEV    |
elk_logstash.1.ek1c7vid194o@ELK2-DEV    | See: 'bin/logstash --help'
elk_logstash.1.ek1c7vid194o@ELK2-DEV    | [ERROR] 2019-01-30 12:11:40.150 [main] Logstash - java.lang.IllegalStateException: Logstash stopped processing because of an error: (SystemExit) exit
```

Any idea why? how can i make my logstash reconfigurable? 
Thanks alot!

**Comment by antoineco** [comment]
@rong0312 you're using the `–` character (unicode: U+2013) instead of the `-` character (unicode: U+002D).

**Comment by rong0312** [comment]
Nice catch!!!
It did remove the error but i cant see my new config taking action when renaming an index's name in logstash's config file (expecting to see another index with the new name).
How do I use this option correctly? is my config right?  

```
logstash:
    image: docker.elastic.co/logstash/logstash:6.5.4
    command: bin/logstash -f /usr/share/logstash/pipeline/logstash.conf --config.reload.automatic 
    ports:
      - "5000:5000"
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
```
