### ISSUE TITLE
ES cpu is not monitored

### ISSUE THREAD

**Issue by rong0312** [deviantony/docker-elk#363]
### Problem description

In Kibana, under the "Monitor" tab, I can't see CPU usage of my Elasticsearch nodes. 
pics attached.

### Extra information

I have enabled this option in my kibana configuration:
>xpack.monitoring.ui.container.elasticsearch.enabled: true

This is what I see when trying to reach CPU data:
![screen shot 2019-02-20 at 10 30 35](https://user-images.githubusercontent.com/33253167/53077418-a4a11800-34fa-11e9-9e03-0d7e066c6d55.png)

And more specific (under one node):

![screen shot 2019-02-20 at 10 30 45](https://user-images.githubusercontent.com/33253167/53077443-aec31680-34fa-11e9-8e7e-b572856e1cc5.png)

#### Stack configuration

```
kibana:
    image: docker.elastic.co/kibana/kibana:6.5.4
    ports:
      - "5601:5601"
    environment:
      server.name: kibana
      server.host: "0"
      elasticsearch.url: http://elasticsearch:9200
      xpack.monitoring.ui.container.elasticsearch.enabled: "true"
```

Any insights? 
Thanks alot!
