### ISSUE TITLE
Logstash volumne: No config files found in path

### ISSUE THREAD

**Issue by weichea** [deviantony/docker-elk#384]
### Problem description

When I ran "_sudo docker-compose run logstash -f ./logstash/config/ingest.conf_", it showed that the config file path cannot be found. However, I could not identified any issue in the configuration. 

### Extra information

```
-rw-rw-r-- 1 logstash logstash  686 Apr 16 02:47 **ingest.conf**
-rw-rw-r-- 1 logstash root     1829 Mar 21 16:23 jvm.options
-rw-r--r-- 1 logstash root      551 Mar 21 16:33 log4j2.properties
-rw-rw-r-- 1 logstash root      342 Mar 21 16:23 logstash-sample.conf
-rw-rw-r-- 1 logstash logstash  227 Apr 12 09:29 logstash.yml
-rw-r--r-- 1 logstash root      286 Mar 21 16:33 pipelines.yml
-rw-rw-r-- 1 logstash root     1696 Mar 21 16:23 startup.options
bash-4.2$ pwd
**/usr/share/logstash/config**
bash-4.2$
```

```
[2019-04-16T08:28:05,224][INFO ][logstash.agent           ] No persistent UUID file found. Generating new UUID {:uuid=>"645e4841-ae42-44f2-b3d5-0fa06cafcf82", :path=>"/usr/share/logstash/data/uuid"}
[2019-04-16T08:28:05,720][INFO ][logstash.config.source.local.configpathloader] No config files found in path {:path=>"/usr/share/**logstash/logstash/**config/ingest.conf"}
[2019-04-16T08:28:05,724][ERROR][logstash.config.sourceloader] No configuration found in the configured sources.
[2019-04-16T08:28:05,988][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
```

#### Stack configuration
```yaml
  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - **./logstash/config/ingest.conf:/usr/share/logstash/config/ingest.conf:ro**
    ports:
      - "5000:5000"
      - "9600:9600"
```

#### Docker setup
Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        e8ff056
 Built:             Thu Apr 11 04:43:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e8ff056
  Built:            Thu Apr 11 04:10:53 2019
  OS/Arch:          linux/amd64
  Experimental:     false

docker-compose version 1.24.0, build 0aa59064
docker-py version: 3.7.2
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018

**Comment by antoineco** [comment]
`-f ./logstash/config/ingest.conf` is pointing to a Logstash file, not a Compose file. The correct command is mentionned in the readme:

```
docker-compose up
```

No parameter needed.

**Comment by weichea** [comment]
@antoineco Thanks for the quick response. 

Sorry, I didn't make myself clear. I wanted to execute a logstash config (for csv file ingestion) with the logstash cointainer thus I try to execute that. i'm not sure if that works or I'm doing it correctly.

**Comment by antoineco** [comment]
Alright, I got it now, you want to start Logstash with a different configuration file than the default `logstash.yml`.

It would be simpler to put your configuration directly inside `logstash.yml`, but if you **really** want to rename it to `ingest.conf`, you'll have to add a custom `command` to your Compose file:

```yaml
  logstash:
    # ...
    command: [ '-f', './logstash/config/ingest.conf' ]
```
