### ISSUE TITLE
apm-server

### ISSUE THREAD

**Issue by einsqing** [deviantony/docker-elk#398]
Failed to connect to backoff(elasticsearch(http://elasticsearch:9200)): Get http://elasticsearch:9200: dial tcp 172.22.0.2:9200: connect: connection refused

**Comment by antoineco** [comment]
What is this issue about? Where are the logs requested in the issue template?

**Comment by einsqing** [comment]
![WX20190531-180017](https://user-images.githubusercontent.com/7685948/58698523-f85eaf80-83cd-11e9-9f5c-af3f5eb1900b.png)

**Comment by einsqing** [comment]
@antoineco default config

```
apm-server:
  host: localhost:8200

output:
  elasticsearch:
    hosts: http://elasticsearch:9200
```
