### ISSUE TITLE
Dynamic cluster using docker-compose with external storage

### ISSUE THREAD

**Issue by Analect** [deviantony/docker-elk#40]
Hi,
Thanks for your project. I can't find a good source for information for setting up a cluster of ES 2.X containers locally (ie. on a single host), which can be dynamically scaled and has the data stored back on the host, using the _-v_ flag.

This is what I've tried:

```
elk:
  image: elasticsearch:2.X
  ports:
    - "9200:9200"
  volumes:
   - /path_on_host_to/data:/path_in_container_to/elasticsearch/data

elkslave:
  image: elasticsearch:2.X
  links:
    - elk:elk
  volumes:
    - /path_on_host_to/data:/path_in_container_to/elasticsearch/data   
    - /path_on_host_to_config/elasticsearch-slave.yml:/etc/elasticsearch/elasticsearch.yml
```

where elasticsearch-slave.yml is:

```
network host: 0.0.0.0
discovery.zen.ping.unicast.hosts: ["elk"]
```

But it doesn't appear to work.

Ideally, I would be able to something like
`docker-compose scale elkslave=3`

**Comment by antoineco** [comment]
@Analect did you solve this issue? Setting up an ES cluster can be relatively complex if you don't know all your nodes in advance.

This project does it on Kubernetes for example: https://github.com/pires/kubernetes-elasticsearch-cluster. It uses a separate "master" for discovery, which allows you to easily scale up your cluster.

I suggested in #33 we create a Wiki page for this kind of setups, could be useful for a lot of people who use this project as an introduction to ES.

**Comment by antoineco** [comment]
Regarding the original problem, I managed to scale my ES cluster by simply disabling static host port mapping and using the internal Docker DNS for [unicast discovery](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html):
```yml
elasticsearch:
  #...
  ports:
      # map to random host ports instead of static ports
      # eg. 32771:9200
    - "9200"
    - "9300"
    environment:
      # use internal Docker DNS for unicast discovery
      discovery.zen.ping.unicast.hosts: elasticsearch
```
Then just scale the number of ES instances up:
```
❯ docker-compose scale elasticsearch=3
Creating and starting centralizedlogging_elasticsearch_2 ... done
Creating and starting centralizedlogging_elasticsearch_3 ... done
```
Your extra nodes should automatically join the current master:
```
❯ docker logs -f centralizedlogging_elasticsearch_2 
...
[2017-03-14T15:51:08,123][INFO ][o.e.c.s.ClusterService   ] [hDXuwLj] detected_master {IFnVp82}{IFnVp82CT--XfrPcrU-ndg}{xBfP-4jNTx2FXVLPlMzLLw}{172.18.0.2}{172.18.0.2:9300}, added {{8pF4rmm}{8pF4rmmoR4uk3pNTQuQ9qQ}{k__zZfnPTQa3-GMFD7_oAw}{172.18.0.6}{172.18.0.6:9300},{IFnVp82}{IFnVp82CT--XfrPcrU-ndg}{xBfP-4jNTx2FXVLPlMzLLw}{172.18.0.2}{172.18.0.2:9300},}, reason: zen-disco-receive(from master [master {IFnVp82}{IFnVp82CT--XfrPcrU-ndg}{xBfP-4jNTx2FXVLPlMzLLw}{172.18.0.2}{172.18.0.2:9300} committed version [39]])
```
If you're using the `x-pack` branch, the nodes will show up in Kibana:
![es_cluster_docker](https://cloud.githubusercontent.com/assets/3299086/23909321/b2b339e8-08d6-11e7-9670-595a17ee9eb1.png)

---

Now if you want to also have separate host volumes, I guess the best approach is to define separate services like `elasticsearch{1,2,3}` in your docker-compose file instead. Use `discovery.zen.ping.unicast.hosts: [ "elasticsearch1", "elasticsearch2", "elasticsearch3" ]` in each of them for clustering, and define your volumes as `/path_on_host_to/data{1,2,3}:/usr/share/elasticsearch/data`.
