### ISSUE TITLE
broke swarm

### ISSUE THREAD

**Issue by gabrieligbastos** [deviantony/docker-elk#404]
### Problem description

I just wanted to deploy it on my swarm cluster,.. i'm trying to follow the bret guide, but using it with aws and some changes...

https://dockercon2018.hubs.vidyard.com/watch/k3Cv676wmxAwYDxbvcgcgC

always when I get into the elk swarm, it just mess up everything, all nodes become timeout and unavailable and eventually the swarm got no manager (i'm using 3 nodes with 3 mgrs)..

what am i missing?

#### Docker setup

Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     true

docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018

**Comment by antoineco** [comment]
Is your cluster already broken or does it become broken as soon as you deploy the Elastic stack?

**Comment by gabrieligbastos** [comment]
Hey,
Thanks for your return.

No, it brokes as soon I deploy ELK.
I just follow de Bret Fisher procedure, dogvscat (repo) with some changes.

I run the ./create-servers.sh

```
#!/usr/bin/env bash

# Print commands
set -x
# Stop on error
set -e

#export AWS_ACCESS_KEY_ID= //on aws configure//
#export AWS_SECRET_ACCESS_KEY= //on aws configure//
export AWS_INSTANCE_TYPE=t2.micro
export AWS_DEFAULT_REGION=us-east-1
export DOCKER_MACHINE_EXECUTABLE="docker-machine"
export NODENUMBER=3
export PREFIX="my.aws."

export PORTS="--amazonec2-open-port 2377 --amazonec2-open-port 7946 --amazonec2-open-port 4789 --amazonec2-open-port 7946/udp --amazonec2-open-port 4789/udp --amazonec2-open-port 8080 --amazonec2-open-port 80 --amazonec2-open-port 443"
export CREATE="$DOCKER_MACHINE_EXECUTABLE create --driver amazonec2"
export REMOVE="$DOCKER_MACHINE_EXECUTABLE rm --force"

# this is a workaround for a bug in aws driver
$CREATE $PORTS ports || true
$REMOVE ports || true
# you may use
# aws ec2 authorize-security-group-ingress --group-name docker-machine --protocol -1 --cidr 0.0.0.0/0
# but I don't like opening all the ports to outside.

function createmachine {
   $CREATE $1
   while [ $? -ne 0 ]; do
        $REMOVE $1
        $CREATE $1
   done
}

for i in $(seq 1 $NODENUMBER)
do
   echo "Starting  ${PREFIX}$i"
   createmachine ${PREFIX}$i &
   sleep 2
done

wait


echo "done"
```

Then, enable monitoring:

```
#!/bin/bash
set -x

# enable monitoring
for server in {1..3}; do
  docker-machine ssh my.aws.${server} 'mkdir -p ~/files' &&
  docker-machine scp daemon.json ubuntu@my.aws.${server}:~/files/ && 
  docker-machine ssh myaws.${server} 'sudo mv /home/ubuntu/files/daemon.json /etc/docker'
  docker-machine ssh my.aws.${server} 'sudo systemctl restart docker' &
done

```

And finally create the swarm..

```
#!/usr/bin/env bash

# Print commands
set -x
# Stop on error
set -e

export DOCKER_MACHINE_EXECUTABLE="docker-machine"
export MANAGERNUMBER=3
export NODENUMBER=3
export PREFIX="my.aws."

$DOCKER_MACHINE_EXECUTABLE ssh ${PREFIX}1 sudo docker swarm init
MANAGERTOKEN=$($DOCKER_MACHINE_EXECUTABLE ssh ${PREFIX}1 sudo docker swarm join-token manager -q)
WORKERTOKEN=$($DOCKER_MACHINE_EXECUTABLE ssh ${PREFIX}1 sudo docker swarm join-token worker -q)
MASTERNODEIP=$($DOCKER_MACHINE_EXECUTABLE ip ${PREFIX}1)

echo $MANAGERTOKEN > manager.token
echo $WORKERTOKEN > worker.token

for i in $(seq 2 $MANAGERNUMBER)
do
   echo "Adding ${PREFIX}$i as manager"
   $DOCKER_MACHINE_EXECUTABLE ssh ${PREFIX}$i sudo docker swarm join \
    --token $MANAGERTOKEN \
    $MASTERNODEIP:2377
done


for i in $(seq $(($MANAGERNUMBER+1)) $NODENUMBER)
do
   echo "Adding ${PREFIX}$i as worker"
   $DOCKER_MACHINE_EXECUTABLE ssh ${PREFIX}$i sudo docker swarm join \
    --token $WORKERTOKEN \
    $MASTERNODEIP:2377
done
```

So, I get everything working on the cloud, just make a:
eval $(docker-machine env my.aws.1)

And start to deploy my stacks..
I deployed the rexray-s3fs plugin:

```
docker plugin install rexray/s3fs \
		LINUX_VOLUME_FILEMODE=0755 \
		S3FS_ACCESSKEY={AWS_ACCESS_KEY} \
		S3FS_SECRETKEY={AWS_ACCESS_SECRET} \
		S3FS_OPTIONS=use_cache=/tmp,allow_other
```

And then, trying to deploy the elk..

```
version: '3.7'

x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "1m" 
  # driver: "gelf"
  # options:
  #   gelf-address: "udp://127.0.0.1:5000"

services:

  elasticsearch:
    <<: *default-opts
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.0
    configs:
      - source: elastic_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    deploy:
      mode: replicated
      replicas: 1

  logstash:
    <<: *default-opts
    image: docker.elastic.co/logstash/logstash-oss:6.4.0
    ports:
      - "5000:5000"
      # - "5000:5000/udp"
      - "9600:9600"
    configs:
      - source: logstash_config
        target: /usr/share/logstash/config/logstash.yml
      - source: logstash_pipeline
        target: /usr/share/logstash/pipeline/logstash.conf
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1

  kibana:
    <<: *default-opts
    image: docker.elastic.co/kibana/kibana-oss:6.4.0
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml
    networks:
      - elk
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.port=5601
        - traefik.docker.network=proxy
        - traefik.frontend.rule=Host:logs.scoob.thrust.com.br
        - traefik.frontend.auth.basic=${KIBANA_USER:-tsk001}:${KIBANA_PASSWORD:-$2y$05$qpGR48GT5te5PVBWHLBd1OuVzY8Lqx1A6jJtXnDm21B/IDveOO27a}
      # TODO: make secrets secret

configs:

  elastic_config:
    file: ./docker-elk/elasticsearch/config/elasticsearch.yml
  logstash_config:
    file: ./docker-elk/logstash/config/logstash.yml
  logstash_pipeline:
    file: ./logstash.conf
  kibana_config:
    file: ./docker-elk/kibana/config/kibana.yml

networks:
  elk:
  proxy:
    external: true

volumes:
  elasticsearch:
    driver: rexray/s3fs
    name: my-logs-elk
    driver_opts:
      size: 10

```

As soon it deploys it mess up the swarm, i get not enough managers online, docker-machine ls gets timeout.. =(
