### ISSUE TITLE
7.2.0 fails to start on docker-swarm

### ISSUE THREAD

**Issue by rong0312** [deviantony/docker-elk#410]
### Problem description

Yesterday I have started working on ELK version upgrade (6.5.4 to 7.2.0).  
Sadly, I came across a lot of problems.  
I am deploying this solution on **docker-swarm,** making the relevant changes  
(like: discovery.zen.ping.unicast.hosts: tasks.elasticsearch  , discovery.type: zen).  
  
I have noticed that some mandatory configurations were added after version 7 like  'cluster.initial_master_nodes', making me a hard time to work on swarm mode.  
I discovered that when I have received this message:
```
"master not discovered yet, this node has not previously joined a bootstrapped (v7+) cluster, and [cluster.initial_master_nodes] is empty on this node: have discovered []... "
```
This results with: 'MasterNotDiscoveredException: null'.

Which then led me to [Bootstrapping a cluster](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-discovery-bootstrap-cluster.html) article, where this error is mentioned.

I can't find a smart way to make my ELK cluster working in **swarm** mode at 7.2.0 version. 
Did anyone make that upgrade and managed to stay alive?

**Comment by antoineco** [comment]
I don't think this is easily doable if you use the default hostname, which is a random ID.
You could maybe try to use predictable hostnames as described [here](https://forums.docker.com/t/generating-a-unique-hostname-for-docker-swarm-service-containers/48194/4?u=antoineco), but the available values are not well documented.

This repository uses [fixed hostnames](https://github.com/jakubhajek/elasticsearch-docker-swarm) as a workaround.

**Comment by rong0312** [comment]
even with your snippet, i am getting the same error:
```
"message": "master not discovered yet, this node has not previously joined a bootstrapped (v7+) cluster, and this node must discover master-eligible nodes [elk_elasticsearch-0, elk_elasticsearch-1, elk_elasticsearch-2] to **bootstrap a cluster: have discovered []; discovery will continue using [10.0.39.6:9300, 10.0.39.7:9300] from hosts providers and** [{elk_elasticsearch.9x3j6damrcxfhm2om576vkp3f.xs60j3s5bo0bzq1hjroaib8nj}{13omqskbQv-cPpQluiSFhQ}{hMyXoE2zQS6T5hYn0lcewQ}{10.0.39.8}{10.0.39.8:9300}{ml.machine_memory=8371490816, xpack.installed=true, ml.max_open_jobs=20}] from last-known cluster state; node term 0, last-accepted version 0 in term 0"  }
```

seems like it won't find via 'cluster.initial_master_nodes' in my case and I don't know why.
Are you using swarm mode as well?

**Comment by antoineco** [comment]
Sorry, the correct format is `elk_elasticsearch.1,elk_elasticsearch.2,elk_elasticsearch.3`. I updated my message.

**Comment by antoineco** [comment]
Actually I'm also having issues with the names. It seems like Swarm adds another random id to the task name:
```
elk_elasticsearch.1.p8d7aufb80h8@docker-desktop    | {"type": "server", "timestamp": "2019-07-01T12:16:51,541+0000", "level": "WARN", "component": "o.e.c.c.ClusterFormationFailureHelper", "cluster.name": "docker-cluster", "node.name": "elk_elasticsearch.1.p8d7aufb80h8f8dwtfcmsyzy4",  "message": "master not discovered yet, this node has not previously joined a bootstrapped (v7+) cluster, and this node must discover master-eligible nodes [elk_elasticsearch.1, elk_elasticsearch.2, elk_elasticsearch.3] to bootstrap a cluster: have discovered [{elk_elasticsearch.2.ofkoacc3wg7a94ahh5nkcma0x}{UfShM0o_TUK28lBtE1Bt-g}{ytSjfbozRKqdSUXNuFdb-Q}{10.0.2.22}{10.0.2.22:9300}{ml.machine_memory=6247051264, ml.max_open_jobs=20, xpack.installed=true}]; discovery will continue using [10.0.2.22:9300] from hosts providers and [{elk_elasticsearch.1.p8d7aufb80h8f8dwtfcmsyzy4}{H2PJbPUDTX2dcUQ2PoZJLg}{e-RvOi-gRuOKT8GNpWppnw}{10.0.2.23}{10.0.2.23:9300}{ml.machine_memory=6247051264, xpack.installed=true, ml.max_open_jobs=20}] from last-known cluster state; node term 0, last-accepted version 0 in term 0"  }
```
I have no idea how to deal with these :(

**Comment by rong0312** [comment]
Yea I was about to write that:(
First of all, thank you for your efforts.
Secondly, do you think this is going to be a problem from now on in this project? (swarm mode)

**Comment by antoineco** [comment]
It's definitely going to become a problem for scaling, unless there is another way to assign predictable names to Swarm tasks.

There is a long discussion about the DNS name at docker/swarmkit#1242, but it doesn't seem to be getting a lot of attention.

**Comment by rong0312** [comment]
Ok so if I understand you correctly the alternative is to split my global mode 'elasticsearch' service to 3 separated elasticsearch services. 
If you don't mind, I will keep this issue opened- in case of future fixes?

**Comment by antoineco** [comment]
I think that's the only alternative for this use case yes, sadly.

We can keep this open for some time but there is currently nothing we can do to fix Swarm's behaviour on our side. A better alternative is probably to use Nomad or Kubernetes.

**Comment by saifat29** [comment]
The following `docker-compose.yml` file worked perfectly for me in both deploy `mode: replicated` and deploy `mode: global` for `elasticsearch:7.2.0` on Docker Swarm-

```yml
version: '3.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    restart: always
    environment:
      - node.name={{.Node.Hostname}}
      - discovery.seed_hosts=elasticsearch
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=node1
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      mode: global
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  es_data:
```

Reference -
- Repo: https://github.com/shazChaudhry/docker-elastic
- File: https://github.com/shazChaudhry/docker-elastic/blob/a49567673395e774510ea843d86074f1525d0fa4/docker-compose.yml

**Comment by antoineco** [comment]
Setting `node.name` to the host name is not a bad idea but will only work if you can be 100% sure there is no more than 1 ES instance per Swarm node.

`discovery.seed_hosts=elasticsearch`, I had no success with this because as far as I understood the option requires a comma delimited list of ES node _names_. Did I get it wrong?

Regarding `cluster.initial_master_nodes`, how can you guarantee that your will have an instance created on "node1" if you have a larger cluster?

**Comment by saifat29** [comment]
Setting `node.name` to the host name works for me because I run only a single ES instance per Swarm mode. It will obviously won't work with multiple ES instances on a single node.

ES documentation about `discovery.seed_hosts`-
When you want to form a cluster with nodes on other hosts, you must use the discovery.seed_hosts setting to provide a list of other nodes in the cluster that are master-eligible and likely to be live and contactable in order to seed the discovery process. This setting should normally contain the addresses of all the master-eligible nodes in the cluster. This setting contains either an array of hosts or a comma-delimited string.
Source - https://www.elastic.co/guide/en/elasticsearch/reference/current/discovery-settings.html

`discovery.seed_hosts=elasticsearch` works in Swarm mode because **maybe** Docker's internal DNS resolves the service name `elasticsearch` to all the other ES instances running in Swarm.
However you are right, the documentation specifically says that it should be a list of master-eligible nodes specified using either an array or a comma-delimited string.

About `cluster.initial_master_nodes`, there is no guarantee that a specific instance will be created on "node1". But this works for me as I have a very small cluster of only 2-3 nodes.
I start my cluster with just an instance on the master swarm node and then only after it is created I join other swarm nodes to the cluster and scale accordingly. This ensures that "node1" is created on the master swarm node.

This method is obviously not for large clusters and is fine for small use cases until some 
elegant solution is found.

**Comment by rong0312** [comment]
@saifat29 
discovery.seed_hosts=elasticsearch gets resolved for sure otherwise how can we explain this behavior ;)
I will wait for some elegant solution as you mentioned or swap to k8s if not possible.

**Comment by deviantony** [comment]
As @antoineco stated above, I think it makes more sense to use `tasks.elasticsearch` instead of `elasticsearch` in the `discovery.seed_hosts` property. Even better, issuing a DNS lookup on `tasks.elasticsearch` and use that as the property value.

`elasticsearch` will will use the virtual IP associated to the service, returning the IP associated to one of the service task (load balanced).

See the Container discovery section in https://docs.docker.com/network/overlay/

**Comment by saifat29** [comment]
I just found a very weird result.
I used the following docker-compose.yml file that is based on using
`{{.Task.Name}}` as `node.name`
`tasks.elasticsearch` as `discovery.seed_hosts` and
`{{.Task.Name}}.1, {{.Task.Name}}.2`, ... as `cluster.initial_master_nodes`

```yml
version: '3.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    restart: always
    environment:
      - node.name={{.Task.Name}}
      - discovery.seed_hosts=tasks.elasticsearch
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=es_stack_elasticsearch.1,es_stack_elasticsearch.2
      - network.host=0.0.0.0
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms3g -Xmx3g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  es_data:
```
Deployed the stack using the following commands-
```bash
docker stack deploy -c docker-compose-1.yml es_stack
docker service scale es_stack_elasticsearch=2
```
(Notice the name of the service `es_stack` to match the `cluster.initial_master_nodes`)

I ran a two node Swarm cluster on https://labs.play-with-docker.com
and it worked perfectly without any catch.
Here is the relevant output of http://x.x.x.x/:9200/_nodes url-
```json
{
	"_nodes": {
		"total": 2,
		"successful": 2,
		"failed": 0
	},
	"cluster_name": "docker-cluster",
	"nodes": {
		"d2T9BoM7TLuj7I18ZgNBaw": {
			"name": "es_stack_elasticsearch.1.3ogomu8v0koz6otr1h0exsk2x",
			"transport_address": "10.0.3.3:9300",
			"host": "10.0.3.3",
			"ip": "10.0.3.3",
			"version": "7.2.0"
		},
		"4zsXxpPdSEaAc5gYYPBBjA": {
			"name": "es_stack_elasticsearch.2.lvqntcfs3saqw5f7n11ghcod7",
			"transport_address": "10.0.3.5:9300",
			"host": "10.0.3.5",
			"ip": "10.0.3.5",
			"version": "7.2.0"
		}
	}
}
```

I tried the exact same thing on a private VPS using the exact same docker version but surprisingly it failed with the same error as @antoineco (https://github.com/deviantony/docker-elk/issues/410#issuecomment-507240891).

I do not understand how exactly this is possible.
You can try for yourself on https://labs.play-with-docker.com

**Comment by antoineco** [comment]
And the cluster formed even if your nodes are named something like `es_stack_elasticsearch.2.lvqntcfs3saqw5f7n11ghcod7` instead of the expected `es_stack_elasticsearch.2`? That's awesome and puzzling at the same time 🤔

**Comment by ranjithvaddepally** [comment]
Has anyone solved the issue, facing same issue with version > 7.0

**Comment by antoineco** [comment]
@ranjithvaddepally it works if you create multiple `elasticsearch` services inside your stack file (es1, es2 and es3 for example), and set the `discovery.seed_hosts` and `cluster.initial_master_nodes` properties to use those names.

There hasn't been any change on the Swarm side, so it is currently the only option I know about.

**Comment by ranjithvaddepally** [comment]
@antoineco thank you for the reply,  we noticed this behaviour with version 7.0, scaling would be not easier, hence we decided to not to upgrade for now until we have a solution for this.

**Comment by antoineco** [comment]
A possible solution to this issue, which I haven't tested yet:

```yaml

services:
  elasticsearch:
    environment:
      node.name: "elk_elasticsearch.{{.Task.Slot}}"
      discovery.type: zen
      discovery.seed_hosts: tasks.elasticsearch
      cluster.initial_master_nodes: elk_elasticsearch.1,elk_elasticsearch.2,elk_elasticsearch.3
```

`{{.Task.Slot}}` supposedly contains the indice part of `{{.Task.Name}}`. E.g. `2` when Task.Name == `elk_elasticsearch.2.p8d7aufb80h`.

I'll try to find time to validate this today or tomorrow.

**Comment by antoineco** [comment]
[Wiki updated](https://github.com/deviantony/docker-elk/wiki/Elasticsearch-cluster). Closing.

Thanks everyone for help and feedback!

**Comment by eoli3n** [comment]
Wiki isn't set to ``discovery_type: zen``, and i'm facing same issue with 7.4.2
```
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.1
    ports:
      - "9200:9200"
      - "9300:9300"
    configs:
      - source: elastic_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      # https://github.com/deviantony/docker-elk/wiki/Elasticsearch-cluster#swarm-mode
      node.name: elk_elasticsearch.{{.Task.Slot}}
      discovery.type: zen
      discovery.seed_hosts: tasks.elasticsearch
      cluster.initial_master_nodes: elk_elasticsearch.1,elk_elasticsearch.2,elk_elasticsearch.3
      node.max_local_storage_nodes: '9'
      ES_JAVA_OPTS: "-Xmx1G -Xms1G"
      ELASTIC_PASSWORD: changeme
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 3
```

Tried both with and without zen discovery_type
I get 
```
elk_elasticsearch.3.5yxdtwrczs91@tspeda-swarm-worker1    | {"type": "server", "timestamp": "2019-12-05T13:31:46,769Z", "level": "WARN", "component": "o.e.c.c.ClusterFormationFailureHelper", "cluster.name": "docker-cluster", "node.name": "elk_elasticsearch.3", "message": "master not discovered yet, this node has not previously joined a bootstrapped (v7+) cluster, and this node must discover master-eligible nodes [elk_elasticsearch.1, elk_elasticsearch.2, elk_elasticsearch.3] to bootstrap a cluster: have discovered [{elk_elasticsearch.3}{t86tzFSnRt-HRCNy8M23eA}{pBC5kfN1SYiCjwPB4m9oLA}{10.0.0.240}{10.0.0.240:9300}{dilm}{ml.machine_memory=4092379136, xpack.installed=true, ml.max_open_jobs=20}]; discovery will continue using [10.0.21.6:9300, 10.0.21.7:9300, 10.0.21.8:9300] from hosts providers and [{elk_elasticsearch.3}{t86tzFSnRt-HRCNy8M23eA}{pBC5kfN1SYiCjwPB4m9oLA}{10.0.0.240}{10.0.0.240:9300}{dilm}{ml.machine_memory=4092379136, xpack.installed=true, ml.max_open_jobs=20}] from last-known cluster state; node term 0, last-accepted version 0 in term 0" }
```
```
