### ISSUE TITLE
Consider moving Elasticsearch credentials to .env

### ISSUE THREAD

**Issue by slhck** [deviantony/docker-elk#443]
This is a suggestion, not a bug report.

Consider using environment variables for the Kibana configuration rather than setting up the passwords in `kibana.yml`. This improves security, as passwords are not saved in files that will be committed.

For example, in the docker-compose.yml file, add:

```
kibana:
    environment:
      ELASTICSEARCH_USERNAME: ${ELASTICSEARCH_USERNAME:-elastic}
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD:-changeme}
    env_file:
      - .env
```

This way, users can set the password via the method shown in the README, and replace it in their `.env`, rather than adding it to the `.yml`.

Would you consider this useful?
