### ISSUE TITLE
Elasticsearch: Timeout while retrying after failure

### ISSUE THREAD

**Issue by farrukhahmed4220** [deviantony/docker-elk#445]
### Problem description
Hello,
I have followed the step as mentioned in README.md 
when I run the command
```
docker-compose up
```
####Docker Logs
It shows that:

```
elasticsearch_1  | {"type": "server", "timestamp": "2019-11-08T07:39:15,442Z", "level": "DEBUG", "component": "o.e.a.a.i.c.TransportCreateIndexAction", "cluster.name": "docker-cluster", "node.name": "1b9502cb0f90", "message": "no known master node, scheduling a retry", "cluster.uuid": "eaGaIfl6QP2c2XAMVPyF_g", "node.id": "jsYGGOSgSpC-QgoSWDdjBA"  }
elasticsearch_1  | {"type": "server", "timestamp": "2019-11-08T07:39:27,190Z", "level": "DEBUG", "component": "o.e.a.a.i.c.TransportCreateIndexAction", "cluster.name": "docker-cluster", "node.name": "1b9502cb0f90", "message": "timed out while retrying [indices:admin/create] after failure (timeout [1m])", "cluster.uuid": "eaGaIfl6QP2c2XAMVPyF_g", "node.id": "jsYGGOSgSpC-QgoSWDdjBA" ,
elasticsearch_1  | "stacktrace": ["org.elasticsearch.cluster.coordination.FailedToCommitClusterStateException: publication failed",
elasticsearch_1  | "at org.elasticsearch.cluster.coordination.Coordinator$CoordinatorPublication$4.onFailure(Coordinator.java:1429) ~[elasticsearch-7.4.1.jar:7.4.1]",
elasticsearch_1  | "at org.elasticsearch.action.ActionRunnable.onFailure(ActionRunnable.java:60) ~[elasticsearch-7.4.1.jar:7.4.1]",
elasticsearch_1  | "at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39) ~[elasticsearch-7.4.1.jar:7.4.1]",
elasticsearch_1  | "at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:225) ~[elasticsearch-7.4.1.jar:7.4.1]",
elasticsearch_1  | "at org.elasticsearch.common.util.concurrent.ListenableFuture.notifyListener(ListenableFuture.java:93) ~[elasticsearch-7.4.1.jar:7.4.1]",
elasticsearch_1  | "at org.elasticsearch.common.util.concurrent.ListenableFuture.addListener(ListenableFuture.java:55) ~[elasticsearch-7.4.1.jar:7.4.1]",
elasticsearch_1  | "at org.elasticsearch.cluster.coordination.Coordinator$CoordinatorPublication.onCompletion(Coordinator.java:1349) ~[elasticsearch-7.4.1.jar:7.4.1]",
elasticsearch_1  | "at org.elasticsearch.cluster.coordination.Publication.onPossibleCompletion(Publication.java:125) ~[elasticsearch-7.4.1.jar:7.4.1]",
elasticsearch_1  | "at org.elasticsearch.cluster.coordination.Publication.cancel(Publication.java:89) ~[elasticsearch-7.4.1.jar:7.4.1]",
elasticsearch_1  | "at org.elasticsearch.cluster.coordination.Coordinator$CoordinatorPublication$2.run(Coordinator.java:1302) ~[elasticsearch-7.4.1.jar:7.4.1]",
elasticsearch_1  | "at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:703) [elasticsearch-7.4.1.jar:7.4.1]",
elasticsearch_1  | "at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]",
elasticsearch_1  | "at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]",
elasticsearch_1  | "at java.lang.Thread.run(Thread.java:830) [?:?]",
elasticsearch_1  | "Caused by: org.elasticsearch.ElasticsearchException: publication cancelled before committing: timed out after 30s",
elasticsearch_1  | "at org.elasticsearch.cluster.coordination.Publication.cancel(Publication.java:86) ~[elasticsearch-7.4.1.jar:7.4.1]",
elasticsearch_1  | "... 5 more"] }
elasticsearch_1  | {"type": "server", "timestamp": "2019-11-08T07:39:27,300Z", "level": "DEBUG", "component": "o.e.a.a.i.c.TransportCreateIndexAction", "cluster.name": "docker-cluster", "node.name": "1b9502cb0f90", "message": "timed out while retrying [indices:admin/create] after failure (timeout [1m])", "cluster.uuid": "eaGaIfl6QP2c2XAMVPyF_g", "node.id": "jsYGGOSgSpC-QgoSWDdjBA" ,

{"type": "server", "timestamp": "2019-11-08T08:19:21,651Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "1b9502cb0f90", "message": "loaded module [x-pack-voting-only-node]" }
{"type": "server", "timestamp": "2019-11-08T08:19:21,668Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "1b9502cb0f90", "message": "loaded module [x-pack-watcher]" }
{"type": "server", "timestamp": "2019-11-08T08:19:21,669Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "1b9502cb0f90", "message": "no plugins loaded" }
{"type": "server", "timestamp": "2019-11-08T08:19:58,454Z", "level": "INFO", "component": "o.e.x.s.a.s.FileRolesStore", "cluster.name": "docker-cluster", "node.name": "1b9502cb0f90", "message": "parsed [0] roles from file [/usr/share/elasticsearch/config/roles.yml]" }
{"type": "server", "timestamp": "2019-11-08T08:20:42,339Z", "level": "INFO", "component": "o.e.x.m.p.l.CppLogMessageHandler", "cluster.name": "docker-cluster", "node.name": "1b9502cb0f90", "message": "[controller/129] [Main.cc@110] controller (64 bit): Version 7.4.1 (Build 973380bdacc5e8) Copyright (c) 2019 Elasticsearch BV" }
{"type": "server", "timestamp": "2019-11-08T08:21:26,940Z", "level": "DEBUG", "component": "o.e.a.ActionModule", "cluster.name": "docker-cluster", "node.name": "1b9502cb0f90", "message": "Using REST wrapper from plugin org.elasticsearch.xpack.security.Security" }
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.

```

My docker-compose.yml: 
```
version: '3.2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      ELASTIC_PASSWORD: changeme
    networks:
      - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    networks:
      - elk
    depends_on:
      - elasticsearch


  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
```

PS: I'm using Standard 2GB Droplet (DigitalOcean) with centos...
