### ISSUE TITLE
How to connect to postgresql from docker elk ?

### ISSUE THREAD

**Issue by NhatThien** [deviantony/docker-elk#457]
### Problem description

I have one question about how to connect docker elk to postgres database installed in local.
In detail, i have a postgres database installed in local. If i run only logstash image in repository `docker_elk/logstash` like following:

    docker build -t "logstash" .
    docker run --network=host logstash

Logstash can connect to postgres.
But when i launch `docker-compose up` with network elk driver bridge, logstash can't connect to postgres. The problem is seem like docker compose doesn't allow to combine network bridge and host at same time.

### Extra information

 My `simple-out.conf` like this:

    input {
        jdbc {
            jdbc_connection_string => "jdbc:postgresql://localhost:5432/logstashtest"
           jdbc_user => "xxx"
        jdbc_driver_library => "/home/tnvan/postgresql-42.2.8.jar"
        jdbc_driver_class => "org.postgresql.Driver"
        jdbc_password => "xxx"
        statement => "SELECT * from contacts"
    }
    }
    output {
    stdout { codec => json_lines }
    elasticsearch{

    hosts => "http://127.0.0.1:9200"
     index => "contact"
    }
    }

#### Docker setup

```
version: '3.2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
    networks:
      - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    command: logstash -f /usr/share/logstash/config/simple-out.conf
    volumes:
      - type: bind
        source: ./logstash/config/simple-out.conf
        target: /usr/share/logstash/config/simple-out.conf
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
networks:
  elk:
    driver: bridge
volumes:
  elasticsearch:
    #db-data:
    #driver: local

```

#### Docker logs
This is the error i get with docker-compose
```
Error: Java::OrgPostgresqlUtil::PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
```
