### ISSUE TITLE
cannot start syslog listener

### ISSUE THREAD

**Issue by hlmtre** [deviantony/docker-elk#46]
cannot run syslog listener on port 514 because (nonexistent) user logstash runs as does not have privileges to start services on ports < 1024. i've tried calling the `docker-compose up` command as root, as well. this is probably because i don't know docker well at all :\

[observe](http://i.imgur.com/SnHYRUp.png)

**Comment by deviantony** [comment]
I do not understand what you are trying to achieve here. Are you just not able to start the stack? Did you made any configuration changes? I'll need more details here in order to help you.

**Comment by hlmtre** [comment]
Sure sure. I'm trying to start logstash with the rest of the services (kibana and elasticsearch), but I have modified the logstash conf like so:
```
    input {
         syslog {}
    }
```
but the service fails to bind to port 514, since that is a privileged kernel-level port. I'm unsure of how to specify the user the service should run as, so it can bind to that port.

**Comment by deviantony** [comment]
Actually, you could just change the port syslog is listening to. Here are my changes:

*logstash.conf*:
```
input {
	syslog {
		port => 5000
	}
}
```

*docker-compose.yml*:
```yml
logstash:
  image: logstash:latest
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
  ports:
    - "5000:5000"
    - "5000:5000/udp"
  links:
    - elasticsearch
```

Then, you can try to send a message to logstash using `netcat`:

```shell
$ nc -w0 -u localhost 5000 <<< "message to logstash via syslog"
```

**Comment by hlmtre** [comment]
I can change the port, but I wanted to replace the listening regular syslog
with logstash on the usual syslog port.

**Comment by deviantony** [comment]
Ok, I found a solution, tell me if it suits your situation.

*logstash.conf*:

```
input {
	syslog { }
}
```

*docker-compose.yml*:

```yml
logstash:
  image: logstash:latest
  command: /opt/logstash/bin/logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
  ports:
    - "514:514"
    - "514:514/udp"
  links:
    - elasticsearch
```

Send a message using `netcat`:

```shell
$ nc -w0 -u localhost 514 <<< "message to logstash via syslog input"
```

Basically, all you need to change is the *command* line of the logstash container in the *docker-compose.yml* file.

Explanation: If you have a look at the logstash image Dockerfile here https://github.com/docker-library/logstash/blob/4f3a81ff0f152003653eecd60d0c4e1f05ce99f0/2.2/Dockerfile you can see that it is using `gosu`. 

`gosu` iis a tool to manage user/permissions and execute a command. You can find more information about it here: https://github.com/tianon/gosu

From the Dockerfile, you can see that an entry point is defined (https://docs.docker.com/engine/reference/builder/#entrypoint), which is the script `docker-entrypoint.sh`. From this script (https://github.com/docker-library/logstash/blob/4f3a81ff0f152003653eecd60d0c4e1f05ce99f0/2.2/docker-entrypoint.sh), you can see the following content: 

```shell
# Run as user "logstash" if the command is "logstash"
if [ "$1" = 'logstash' ]; then
	set -- gosu logstash "$@"
fi
```

So if you run any `logstash` command in the container, it will be started with the *logstash* user. The trick here is to pass the full path to logstash binary to avoid the `gosu` setup, i.e: `/opt/logstash/bin/logstash`
