### ISSUE TITLE
forbidden request: RUM endpoint is disabled. Configure the `apm-server.rum` section in apm-server.yml to enable ingestion of RUM events

### ISSUE THREAD

**Issue by inandi** [deviantony/docker-elk#479]
my project directory (using default structure, except these files below)

![Screenshot (17)](https://user-images.githubusercontent.com/33930347/78407249-f97df000-7621-11ea-9ffc-b1182ca6e3a8.png)
 
added a index.html file to use RUM

```
<!DOCTYPE html>
<html>
<head>
	<title>Index</title>
</head>
<body>
	<p>hello worlde</p>
</body>
<script src="https://unpkg.com/@elastic/apm-rum@4.0.1/dist/bundles/elastic-apm-rum.umd.min.js">
</script>
<script>
	elasticApm.init({
		serviceName: 'test',
		serverUrl: 'http://localhost:8200',
		serviceVersion: '0.90'
	})
</script>
</html>
```

but in  browser i am getting this error

> {
>   "error": "forbidden request: RUM endpoint is disabled. Configure the `apm-server.rum` section in apm-server.yml to enable ingestion of RUM events. If you are not using the RUM agent, you can safely ignore this error."
> }

![Screenshot (18)](https://user-images.githubusercontent.com/33930347/78407539-b2442f00-7622-11ea-8479-9788059dacc4.png)

made little change in **docker-elk\extensions\apm-server\config\apm-server.yml**

```
apm-server:
  host: 0.0.0.0:8200

output:
  elasticsearch:
    hosts: ['http://elasticsearch:9200']
    username: elastic
    password: changeme
rum:
# To enable real user monitoring (RUM) support set this to true.
  enabled: true
```

thanks in advance !!!! cheers :)
