### ISSUE TITLE
logstash exit 0

### ISSUE THREAD

**Issue by kilinochi** [deviantony/docker-elk#481]
### Problem description

I'm trying to use logstash to synchronize data between mongodb and elastichsearch

### Extra information

My project structure looks like 
[
![image](https://user-images.githubusercontent.com/34065879/79530238-732cc980-8077-11ea-916a-4256ec127276.png)
](url)

comics.conf looks like 

```
input {
  mongodb {
    uri => "mongodb://mongo:picstories@picstories:27017/picstories?authSource=picstories&replicaSet=rs0"
    placeholder_db_dir => "/opt/logstash"
    placeholder_db_name => "logstash_sqlite.db"
    collection => "comics"
    batch_size => 500
    type => "comics"
  }
}

output {
  stdout {
    codec => rubydebug
  }
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "picstories"
    docoment_type => "comics"
  }
}
```

and pages.cong looks like 

```
input {
  mongodb {
    uri => "mongodb://mongo:picstories@picstories:27017/picstories?authSource=picstories&replicaSet=rs0"
    placeholder_db_dir => "/opt/logstash"
    placeholder_db_name => "logstash_sqlite.db"
    collection => "pages"
    batch_size => 500
    type => "pages"
  }
}

output {
  stdout {
    codec => rubydebug
  }
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "picstories"
    docoment_type => "pages"
  }
}
```

and pipelines.yml looks like

```
- pipeline.id: comics-config
  pipeline.workers: 1
  pipeline.batch.size: 1
  path.config: "./pipelines/comics.conf"

- pipeline.id: pages-config
  pipeline.workers: 1
  pipeline.batch.size: 1
  path.config: "./pipelines/pages.conf"
```

#### Docker setup

```
version: '3'
networks:
  kafka-net:
    driver: bridge
volumes:
  esdata:
    driver: local
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    container_name: elasticsearch
    deploy:
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 20M
    environment:
      - discovery.type=single-node
    restart: always
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - kafka-net
  mongo:
    image: mongo
    container_name: mongo-db
    restart: always
    networks:
      - kafka-net
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    ports:
      - '27017:27017'
  zookeeper-server:
    image: 'wurstmeister/zookeeper:latest'
    container_name: zookeeper
    networks:
      - kafka-net
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka-server:
    image: 'wurstmeister/kafka:latest'
    container_name: kafka
    ports:
      - '9092:9092'
    networks:
      - kafka-net
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-server:2181
      KAFKA_CREATE_TOPICS_SEPARATOR: "$$'\n'"
      KAFKA_CREATE_TOPICS: |
        parse-comic-task:1:1
         update-comic-task:1:1
    depends_on:
      - zookeeper-server
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.1
    container_name: kibana
    ports:
      - "5601:5601"
    links:
      - elasticsearch:elasticsearch
    networks:
      - kafka-net
  mongosetup:
    image: mongo
    container_name: mongosetup
    depends_on:
      - mongo
    volumes:
      - .:/scripts
    networks:
      - kafka-net
    restart: "no"
    entrypoint: [ "bash", "/scripts/mongo_setup.sh"]
  logstash:
    image: docker.elastic.co/logstash/logstash:7.6.2
    command: bash -c "cd bin && logstash-plugin install logstash-input-mongodb && logstash-plugin install logstash-output-elasticsearch"
    #build: .
    container_name: logstash
    depends_on:
      - mongo
      - elasticsearch
    networks:
      - kafka-net
    ports:
      - 5046:5046
    volumes:
      - ./config/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./config/pipelines:/usr/share/logstash/config/pipelines:ro
    restart: "no"
```

#### Docker logs

```
logstash            | Installation successful
logstash            | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
logstash            | WARNING: An illegal reflective access operation has occurred
logstash            | WARNING: Illegal reflective access by com.headius.backport9.modules.Modules to method sun.nio.ch.NativeThread.signal(long)
logstash            | WARNING: Please consider reporting this to the maintainers of com.headius.backport9.modules.Modules
logstash            | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
logstash            | WARNING: All illegal access operations will be denied in a future release
logstash            | Validating logstash-output-elasticsearch
logstash            | Installing logstash-output-elasticsearch
logstash            | Installation successful
logstash exited with code 0
```

**Comment by antoineco** [comment]
You're overriding `command` with a bash script, so the logstash container executes the script, then returns without running Logstash.

Have you read this [How to add plugins](https://github.com/deviantony/docker-elk/blob/master/README.md#how-to-add-plugins)?

**Comment by kilinochi** [comment]
So, yes, I have done next steps: 

- in Dockerfile :  
```
FROM docker.elastic.co/logstash/logstash:7.6.2
RUN logstash-plugin install 
RUN logstash-plugin install logstash-input-mongodb-0.3.0.gem
RUN logstash-plugin install logstash-output-elasticsearch
```

- docker-compose 
```
logstash:
    image: docker.elastic.co/logstash/logstash:7.6.2
    build: .
    container_name: logstash
    entrypoint: ["bash", "/scripts/logstash.sh"]
    environment:
      XPACK_MONITORING_ENABLED: "false"
    depends_on:
      - mongo
      - elasticsearch
    networks:
      - kafka-net
    ports:
      - 5046:5046
    volumes:
      - ./config/pipelines.yml:/usr/share/logstash/config/pipelines.yml:rw
      - ./config/pipelines:/usr/share/logstash/config/pipelines:rw
      - .:/scripts
    restart: "no"

```

logstash.sh
```
#!/bin/bash
echo "****************start logstash script***********************************"
mkdir /opt/logstash-mongodb/
# Sample usage when no commands is given outside
bin/logstash -f /usr/share/logstash/config/pipelines.yml
```

and comics and pages conf files

Comics
```
input {
  mongodb {
    uri => 'mongodb://mongo:picstories@picstories:27017/picstories?authSource=picstories&replicaSet=rs0'
    placeholder_db_dir => '/opt/logstash'
    placeholder_db_name => 'logstash_sqlite.db'
    collection => 'comics'
    batch_size => 500
    type => 'comics'
  }
}

output {
  stdout {
    codec => rubydebug
  }
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => 'picstories'
    docoment_type => 'comics'
    action => 'index'
  }
}
```
Pages 
```
input {
  mongodb {
    uri => 'mongodb://mongo:picstories@picstories:27017/picstories?authSource=picstories&replicaSet=rs0'
    placeholder_db_dir => '/opt/logstash'
    placeholder_db_name => 'logstash_sqlite.db'
    collection => 'pages'
    batch_size => 500
    type => 'pages'
  }
}

output {
  stdout {
    codec => rubydebug
  }
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => 'picstories'
    docoment_type => 'pages'
    action => 'index'
  }
}
```


Now I have next error



```
logstash            | [2020-04-17T08:21:45,932][INFO ][logstash.licensechecker.licensereader] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://elasticsearch:9200/]}}
logstash            | [2020-04-17T08:21:46,246][WARN ][logstash.licensechecker.licensereader] Restored connection to ES instance {:url=>"http://elasticsearch:9200/"}
logstash            | [2020-04-17T08:21:46,356][INFO ][logstash.licensechecker.licensereader] ES Output version determined {:es_version=>7}
logstash            | [2020-04-17T08:21:46,360][WARN ][logstash.licensechecker.licensereader] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
logstash            | [2020-04-17T08:21:46,660][INFO ][logstash.monitoring.internalpipelinesource] Monitoring License OK
logstash            | [2020-04-17T08:21:46,662][INFO ][logstash.monitoring.internalpipelinesource] Validated license for monitoring. Enabling monitoring pipeline.
logstash            | [2020-04-17T08:21:47,161][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"LogStash::ConfigurationError", :message=>"Expected one of [ \\t\\r\\n], \"#\", \"input\", \"filter\", \"output\" at line 1, column 1 (byte 1)", :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:41:in `compile_imperative'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:49:in `compile_graph'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:11:in `block in compile_sources'", "org/jruby/RubyArray.java:2580:in `map'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:10:in `compile_sources'", "org/logstash/execution/AbstractPipelineExt.java:161:in `initialize'", "org/logstash/execution/JavaBasePipelineExt.java:47:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:27:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:36:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:326:in `block in converge_state'"]}
logstash            | [2020-04-17T08:21:47,462][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"LogStash::ConfigurationError", :message=>"Expected one of [ \\t\\r\\n], \"#\", \"input\", \"filter\", \"output\" at line 1, column 1 (byte 1)", :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:41:in `compile_imperative'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:49:in `compile_graph'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:11:in `block in compile_sources'", "org/jruby/RubyArray.java:2580:in `map'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:10:in `compile_sources'", "org/logstash/execution/AbstractPipelineExt.java:161:in `initialize'", "org/logstash/execution/JavaBasePipelineExt.java:47:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:27:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:36:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:326:in `block in converge_state'"]}
logstash            | [2020-04-17T08:21:49,759][INFO ][logstash.outputs.elasticsearch][.monitoring-logstash] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://elasticsearch:9200/]}}
logstash            | [2020-04-17T08:21:49,777][WARN ][logstash.outputs.elasticsearch][.monitoring-logstash] Restored connection to ES instance {:url=>"http://elasticsearch:9200/"}
logstash            | [2020-04-17T08:21:49,790][INFO ][logstash.outputs.elasticsearch][.monitoring-logstash] ES Output version determined {:es_version=>7}
logstash            | [2020-04-17T08:21:49,791][WARN ][logstash.outputs.elasticsearch][.monitoring-logstash] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
logstash            | [2020-04-17T08:21:49,845][INFO ][logstash.outputs.elasticsearch][.monitoring-logstash] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["http://elasticsearch:9200"]}
logstash            | [2020-04-17T08:21:50,015][INFO ][logstash.javapipeline    ][.monitoring-logstash] Starting pipeline {:pipeline_id=>".monitoring-logstash", "pipeline.workers"=>1, "pipeline.batch.size"=>2, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>2, "pipeline.sources"=>["monitoring pipeline"], :thread=>"#<Thread:0x5e8e8911 run>"}
logstash            | [2020-04-17T08:21:50,979][INFO ][logstash.javapipeline    ][.monitoring-logstash] Pipeline started {"pipeline.id"=>".monitoring-logstash"}
logstash            | [2020-04-17T08:21:51,343][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
logstash            | [2020-04-17T08:21:52,184][INFO ][logstash.javapipeline    ] Pipeline terminated {"pipeline.id"=>".monitoring-logstash"}
logstash            | [2020-04-17T08:21:52,924][INFO ][logstash.runner          ] Logstash shut down.
logstash            | ****************start logstash script***********************************
logstash exited with code 0

```


So, google say that I can not have in one indexes more types in elastic since 6 version, can I  resolve this avoiding create two databases in mongodb?
