### ISSUE TITLE
Error creating 3 nodes Elasticsearch in docker

### ISSUE THREAD

**Issue by securigeek** [deviantony/docker-elk#499]
Hello ,

I am pretty new with docker and have been tasked with testing the complete ELK cluster on docker . WIth the example given on the website it only has 2 nodes and hence I reused the format to add a 3node in thedocker-compose file. But when I try to compose-up I get the following error message :

`ERROR: yaml.parser.ParserError: while parsing a block mapping
in "./docker-compose.yml", line 34, column 5
expected , but found ''
in "./docker-compose.yml", line 55, column 6

docker-compose.yml :
```yaml
version: '2.2'

services:
es01:
container_name: es01
image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
environment:
- node.name=es01
- discovery.seed_hosts=es02,es03
- cluster.initial_master_nodes=es01,es02,es03
- ELASTIC_PASSWORD=$ELASTIC_PASSWORD
- "ES_JAVA_OPTS=-Xms512m -Xmx512m"
- xpack.license.self_generated.type=basic
- xpack.security.enabled=true
- xpack.security.http.ssl.enabled=true
- xpack.security.http.ssl.key=$CERTS_DIR/es01/es01.key
- xpack.security.http.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
- xpack.security.http.ssl.certificate=$CERTS_DIR/es01/es01.crt
- xpack.security.transport.ssl.enabled=true
- xpack.security.transport.ssl.verification_mode=certificate
- xpack.security.transport.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
- xpack.security.transport.ssl.certificate=$CERTS_DIR/es01/es01.crt
- xpack.security.transport.ssl.key=$CERTS_DIR/es01/es01.key
volumes: ['data01:/usr/share/elasticsearch/data', 'certs:$CERTS_DIR']
ports:
- 9200:9200
healthcheck:
test: curl --cacert $CERTS_DIR/ca/ca.crt -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
interval: 30s
timeout: 10s
retries: 5

es02:
container_name: es02
image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
environment:
- node.name=es02
- discovery.seed_hosts=es02,es03
- cluster.initial_master_nodes=es01,es02,es03
- ELASTIC_PASSWORD=$ELASTIC_PASSWORD
- "ES_JAVA_OPTS=-Xms512m -Xmx512m"
- xpack.license.self_generated.type=basic
- xpack.security.enabled=true
- xpack.security.http.ssl.enabled=true
- xpack.security.http.ssl.key=$CERTS_DIR/es02/es02.key
- xpack.security.http.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
- xpack.security.http.ssl.certificate=$CERTS_DIR/es02/es02.crt
- xpack.security.transport.ssl.enabled=true
- xpack.security.transport.ssl.verification_mode=certificate
- xpack.security.transport.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
- xpack.security.transport.ssl.certificate=$CERTS_DIR/es02/es02.crt
- xpack.security.transport.ssl.key=$CERTS_DIR/es02/es02.key
volumes: ['data02:/usr/share/elasticsearch/data', 'certs:$CERTS_DIR']
ports:
- 9200:9200

es03:
container_name: es03
image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
environment:
- node.name=es03
- discovery.seed_hosts=es01,es02
- cluster.initial_master_nodes=es01,es02,es03
- ELASTIC_PASSWORD=$ELASTIC_PASSWORD
- "ES_JAVA_OPTS=-Xms512m -Xmx512m"
- xpack.license.self_generated.type=basic
- xpack.security.enabled=true
- xpack.security.http.ssl.enabled=true
- xpack.security.http.ssl.key=$CERTS_DIR/es01/es03.key
- xpack.security.http.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
- xpack.security.http.ssl.certificate=$CERTS_DIR/es03/es03.crt
- xpack.security.transport.ssl.enabled=true
- xpack.security.transport.ssl.verification_mode=certificate
- xpack.security.transport.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
- xpack.security.transport.ssl.certificate=$CERTS_DIR/es01/es03.crt
- xpack.security.transport.ssl.key=$CERTS_DIR/es03/es03.key
volumes: ['data03:/usr/share/elasticsearch/data', 'certs:$CERTS_DIR']
ports:
- 9200:9200

wait_until_ready:
	image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
	command: /usr/bin/true
	depends_on: {"es01": {"condition": "service_healthy"}}

volumes: {"data01", "data02","data03" "certs"}
```
  
  
  Please help. 
Thanks in advance.

**Comment by antoineco** [comment]
You have quotes around `"ES_JAVA_OPTS=-Xms512m -Xmx512m"`. Please remove them.

**Comment by securigeek** [comment]
Thank you for the response 
I removed them from every instance 
and then ran docker-compose up -d 

output :

[scure@localhost elk]$ docker-compose up -d
ERROR: yaml.parser.ParserError: while parsing a block mapping
  in "./docker-compose.yml", line 34, column 5
expected <block end>, but found '<block mapping start>'
  in "./docker-compose.yml", line 55, column 6

**Comment by antoineco** [comment]
Could you please post your Compose file between triple backticks? (\`\`\`(compose.yaml)\`\`\`) The one you pasted in the issue is not indented correctly. For example
```yaml
services:
es01:
container_name: es01
```
should be
```yaml
services:
  es01:
    container_name: es01
```
Right now I have no idea if this is just how GitHub displays it or if you really wrote your compose file this way.

---

On another note, I will now close your issue because it is unrelated to `docker-elk` (you are not using our Compose file obviously). I will keep responding to you here even it the issue is closed, but in the future please use https://forums.docker.com/ instead.
