### ISSUE TITLE
working in dev and same set-up not working in prod

### ISSUE THREAD

**Issue by bhanupraveeng** [deviantony/docker-elk#519]
### Problem description
Working in dev environment. Once moved to production server, facing issues as below:
```
kibana_1         | {"type":"log","@timestamp":"2020-07-20T08:32:27Z","tags":["warning","elasticsearch","admin"],"pid":6,"message":"No living connections"}
kibana_1         | {"type":"log","@timestamp":"2020-07-20T08:32:29Z","tags":["warning","elasticsearch","admin"],"pid":6,"message":"Unable to revive connection: http://10.206.2.97:9200/"}
```

### Extra information
```
kibana_1         | {"type":"log","@timestamp":"2020-07-20T08:32:27Z","tags":["warning","elasticsearch","admin"],"pid":6,"message":"No living connections"}
kibana_1         | {"type":"log","@timestamp":"2020-07-20T08:32:29Z","tags":["warning","elasticsearch","admin"],"pid":6,"message":"Unable to revive connection: http://10.206.2.97:9200/"}
```

#### Stack configuration
Docker-compose.yml
```
version: '3.2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data   
    ports:
      - "9200:9200"
      - "9300:9300"
    container_name: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xmx2g -Xms2g"
      discovery.type: single-node
    networks:
      - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./logstash/config/
        target: /usr/share/logstash/config/
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
```
Elasticsearch.yml
```
---
## Default Elasticsearch configuration from Elasticsearch base image.
## https://github.com/elastic/elasticsearch/blob/master/distribution/docker/src/docker/config/elasticsearch.yml
#
cluster.name: "docker-cluster"
node.name: 10.206.2.97

network.host: 0.0.0.0
network.publish_host: 10.206.2.97

## X-Pack settings
## see https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-xpack.html
#
xpack.license.self_generated.type: trial
xpack.security.enabled: false
xpack.monitoring.collection.enabled: true
```
kibana.yml

```
server.name: kibana
server.host: 0.0.0.0
elasticsearch.hosts: [ "http://10.206.2.97:9200" ]
monitoring.ui.container.elasticsearch.enabled: true
elasticsearch.requestTimeout: 120000
elasticsearch.ssl.verificationMode: none

elasticsearch.username: elastic
elasticsearch.password: healthcenter@123
```

#### Docker setup

```
[m2480@amberroad.com@pla11010 docker-elk]$ docker version
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.39
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:46:54 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:06:30 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

```
docker-compose version 1.26.0, build d4451659
docker-py version: 4.2.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```
#### Docker logs

```

kibana_1         | {"type":"log","@timestamp":"2020-07-20T08:32:24Z","tags":["warning","elasticsearch","monitoring"],"pid":6,"message":"No living connections"}
kibana_1         | {"type":"log","@timestamp":"2020-07-20T08:32:24Z","tags":["warning","plugins","licensing"],"pid":6,"message":"License information could not be obtained from Elasticsearch due to Error: No Living connections error"}
kibana_1         | {"type":"log","@timestamp":"2020-07-20T08:32:24Z","tags":["warning","elasticsearch","admin"],"pid":6,"message":"Unable to revive connection: http://10.206.2.97:9200/"}
kibana_1         | {"type":"log","@timestamp":"2020-07-20T08:32:24Z","tags":["warning","elasticsearch","admin"],"pid":6,"message":"No living connections"}
kibana_1         | {"type":"log","@timestamp":"2020-07-20T08:32:27Z","tags":["warning","elasticsearch","admin"],"pid":6,"message":"Unable to revive connection: http://10.206.2.97:9200/"}
kibana_1         | {"type":"log","@timestamp":"2020-07-20T08:32:27Z","tags":["warning","elasticsearch","admin"],"pid":6,"message":"No living connections"}
kibana_1         | {"type":"log","@timestamp":"2020-07-20T08:32:29Z","tags":["warning","elasticsearch","admin"],"pid":6,"message":"Unable to revive connection: http://10.206.2.97:9200/"}
```
