### ISSUE TITLE
Unable to start kibana

### ISSUE THREAD

**Issue by RobWalker** [deviantony/docker-elk#53]
I admit to not knowing a lot about docker and/or ELK, but when I try and start the stack using a freshly cloned repo, no changes on a clean CentOS 7 VM I get:

![image](https://cloud.githubusercontent.com/assets/736849/15302426/e9697982-1b80-11e6-9f0d-648226f517e1.png)

My google-fu has failed to find anything obvious, am I missing something there?

**Comment by norbertkorodi** [comment]
Could you pls check if this commit [https://github.com/deviantony/docker-elk/pull/54/commits/c9eb9eb404784a275363af943209e0d483f53ef5](url) solves the problem for you as well?

**Comment by deviantony** [comment]
Could you try to replace the definition of the Kibana container in the `docker-compose.yml` file by the following:

```yml
kibana:
  build: kibana/
  volumes:
    - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
  ports:
    - "5601:5601"
  links:
    - elasticsearch
```
