### ISSUE TITLE
Swarm mode with multiple hosts

### ISSUE THREAD

**Issue by victorpintot8** [deviantony/docker-elk#548]
Hi! Does it work in swarm mode with multiple worker hosts?. I have tried using your stack, but i only works well in sigle node mode.
Thanks in advance.

For the record, i'm using the following stack file:

```yaml
version: '3.3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    ports:
      - '9200'
      - '9300'
    configs:
      - source: elastic_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    volumes:
      - elasticsearch1-data:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      node.name: elk_elasticsearch.{{.Task.Slot}}
      discovery.type: ''
      discovery.seed_hosts: tasks.elasticsearch
      cluster.initial_master_nodes: elk_elasticsearch.1,elk_elasticsearch.2,elk_elasticsearch.3
      node.max_local_storage_nodes: '3'
      ELASTIC_PASSWORD: changeme
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 3

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    ports:
      - "5601:5601"
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1

configs:
  elastic_config:
    file: ./elasticsearch/config/elasticsearch.yml
  kibana_config:
    file: ./kibana/config/kibana.yml

volumes:
  elasticsearch1-data:

networks:
  elk:
    driver: overlay
```

And the error log is:

> {"type": "server", "timestamp": "2020-10-25T04:09:55,293Z", "level": "WARN", "component": "o.e.d.HandshakingTransportAddressConnector", "cluster.name": "docker-cluster", "node.name": "elk_elasticsearch.1", "message": "[connectToRemoteMasterNode[10.0.29.8:9300]] completed handshake with [{elk_elasticsearch.3}{UMNabUPhSpex83cBELaZHA}{ImNBkSx8QlmglVXcVr9bbQ}{10.0.0.227}{10.0.0.227:9300}{dilmrt}{ml.machine_memory=2084179968, ml.max_open_jobs=20, xpack.installed=true, transform.node=true}] but followup connection failed", 
"stacktrace": ["org.elasticsearch.transport.ConnectTransportException: [elk_elasticsearch.3][10.0.0.227:9300] connect_timeout[30s]",
"at org.elasticsearch.transport.TcpTransport$ChannelsConnectedListener.onTimeout(TcpTransport.java:972) ~[elasticsearch-7.9.2.jar:7.9.2]",
"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:678) ~[elasticsearch-7.9.2.jar:7.9.2]",
"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]",
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]",
"at java.lang.Thread.run(Thread.java:832) [?:?]"] }
{"type": "server", "timestamp": "2020-10-25T04:10:05,194Z", "level": "WARN", "component": "o.e.c.c.ClusterFormationFailureHelper", "cluster.name": "docker-cluster", "node.name": "elk_elasticsearch.1", "message": "master not discovered yet, this node has not previously joined a bootstrapped (v7+) cluster, and this node must discover master-eligible nodes [elk_elasticsearch.1, elk_elasticsearch.2, elk_elasticsearch.3] to bootstrap a cluster: have discovered [{elk_elasticsearch.1}{c0ChvcqfR9GFtWu7doUBQA}{pkFEDFETSYa3aIjDx6vQeA}{10.0.0.225}{10.0.0.225:9300}{dilmrt}{ml.machine_memory=2084401152, xpack.installed=true, transform.node=true, ml.max_open_jobs=20}]; discovery will continue using [10.0.29.6:9300, 10.0.29.8:9300, 10.0.29.7:9300] from hosts providers and [{elk_elasticsearch.1}{c0ChvcqfR9GFtWu7doUBQA}{pkFEDFETSYa3aIjDx6vQeA}{10.0.0.225}{10.0.0.225:9300}{dilmrt}{ml.machine_memory=2084401152, xpack.installed=true, transform.node=true, ml.max_open_jobs=20}] from last-known cluster state; node term 0, last-accepted version 0 in term 0" }
