### ISSUE TITLE
logstash permission denied

### ISSUE THREAD

**Issue by ismailazerty** [deviantony/docker-elk#568]
Hello,
  I have this error with logstash : retrying failed action with response code: 403 ({"type"=>"security_exception", "reason"=>"no permissions for [indices:data/write/index, indices:data/write/bulk[s]] and User [name=logstash, backend_roles=[logstash], requestedTenant=null]"})
 
  any idea ?

Thx

**Comment by antoineco** [comment]
To me it sounds like the following role mapping wasn't applied to the `logstash` user:

https://github.com/deviantony/docker-elk/blob/2d4e1b65ce53715224e47f2c205efcf40d3c9c4e/elasticsearch/config/sg/sg_roles_mapping.yml#L21-L23

I can't tell for sure with that little information though.

I just tried with the default configuration on the `searchguard` branch, and Logstash seems to work as expected: I get data into Elasticsearch and no error in the logs. Any way I can reproduce this?

**Comment by antoineco** [comment]
@ismailazerty friendly ping. Do you have more information that could help me reproduce that issue, like samples of configuration files and full logs?

**Comment by antoineco** [comment]
Maybe Logstash was configured to push data to an index which doesn't match the `logstash-*` or `*beat*` patterns?

**Comment by ismailazerty** [comment]
Exactly. my index doesn't match the logstash-* or *beat* patterns. How can I configure this ?

**Comment by antoineco** [comment]
(Note: that's the reason why we ask users to fill the [issue template](https://github.com/deviantony/docker-elk/blob/d352d00/.github/ISSUE_TEMPLATE.md). With that information, I could have provided you with an immediate answer.)

Here is an example of role you can assign to your `logstash` user to give it the permissions it requires. Simply replace `my-index-pattern-*` with something suitable for your use case (can contain [wildcards](https://docs.search-guard.com/latest/roles-permissions#dynamic-index-patterns-wildcards-and-regular-expressions)).

```yaml
# elasticsearch/config/sg/sg_roles.yml

# -- Add at the end of the file --

logstash_custom_index:
  index_permissions:
    - index_patterns:
        - my-index-pattern-*
      allowed_actions:
        - CRUD
        - CREATE_INDEX
        - MANAGE
```


```yaml
# elasticsearch/config/sg/sg_roles_mapping.yml

# -- Add at the end of the file --

logstash_custom_index:
  users:
    - logstash
```
