### ISSUE TITLE
Is filebeat integrated with this project ?

### ISSUE THREAD

**Issue by bygzyz** [deviantony/docker-elk#586]
Is filebeat integrated with this project

**Comment by antoineco** [comment]
We have the Beats input enabled on TCP port 5044 in Logstash. That means you can configure your Filebeat agents to send data to that port, if that was the question.

**Comment by antoineco** [comment]
Extra note: Filebeat can be configured to communicate either with Logstash or with Elasticsearch directly.

References:
* https://www.elastic.co/guide/en/beats/filebeat/7.12/logstash-output.html
* https://www.elastic.co/guide/en/beats/filebeat/7.12/elasticsearch-output.html

Examples:

_Replace "my_elastic_stack" with the host name or IP address where the stack is reachable from your Filebeat agents._

```yaml
output.logstash:
  hosts: ['my_elastic_stack:5044']
```

```yaml
output.elasticsearch:
  hosts: ['http://my_elastic_stack:9200']
  username: elastic
  password: changeme
```
