### ISSUE TITLE
Enabling https on Kibana

### ISSUE THREAD

**Issue by Arcuza** [deviantony/docker-elk#670]
I had a configuration for 7.17.0 which enabled https for Kibana. However that configuration doesn't work for 8.0.0.

```
 kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    environment:
      - SERVER_SSL_ENABLED=true
      - SERVER_SSL_CERTIFICATE=/usr/share/kibana/config/kibana.cert
      - SERVER_SSL_KEY=/usr/share/kibana/config/kibana.key
      - SERVER_SSL_CERTIFICATEAUTHORITIES=/usr/share/kibana/config/lets-encrypt-r3.pem
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
      - type: bind
        source: ./kibana/config/kibana.cert
        target: /usr/share/kibana/config/kibana.cert
        read_only: true
      - type: bind
        source: ./kibana/config/kibana.key
        target: /usr/share/kibana/config/kibana.key
        read_only: true
      - type: bind
        source: ./kibana/config/lets-encrypt-r3.pem
        target: /usr/share/kibana/config/lets-encrypt-r3.pem
```

Could you please add information on how to enable https for Kibana within the docker-compose configurations using a  self provided cert and key file?

Thank you very much!
