### ISSUE TITLE
Can't authenticate with Elastiscsearch, Kibana server is not ready yet

### ISSUE THREAD

**Issue by antoineco** [deviantony/docker-elk#680]
_Originally posted by @asgharkhan in https://github.com/deviantony/docker-elk/issues/677#issuecomment-1058333365_

---

Hi, 
I am using 
docker-compose version 1.29.2, build 5becea4c

and docker-compose config output is below 
```yaml
networks:
  elk:
    driver: bridge
services:
  elasticsearch:
    build:
      args:
        ELASTIC_VERSION: 8.0.0
      context: /Library/WebServer/Documents/docker/docker-elk/elasticsearch
    environment:
      ELASTIC_PASSWORD: changeme
      ES_JAVA_OPTS: -Xmx256m -Xms256m
      discovery.type: single-node
    networks:
      elk: null
    ports:
    - published: 9200
      target: 9200
    - published: 9300
      target: 9300
    volumes:
    - /Library/WebServer/Documents/docker/docker-elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
    - elasticsearch:/usr/share/elasticsearch/data:z
  kibana:
    build:
      args:
        ELASTIC_VERSION: 8.0.0
      context: /Library/WebServer/Documents/docker/docker-elk/kibana
    depends_on:
      elasticsearch:
        condition: service_started
    environment:
      KIBANA_SYSTEM_PASSWORD: changeme
    networks:
      elk: null
    ports:
    - published: 5601
      target: 5601
    volumes:
    - /Library/WebServer/Documents/docker/docker-elk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
  logstash:
    build:
      args:
        ELASTIC_VERSION: 8.0.0
      context: /Library/WebServer/Documents/docker/docker-elk/logstash
    depends_on:
      elasticsearch:
        condition: service_started
    environment:
      LOGSTASH_INTERNAL_PASSWORD: changeme
      LS_JAVA_OPTS: -Xmx256m -Xms256m
    networks:
      elk: null
    ports:
    - published: 5044
      target: 5044
    - protocol: tcp
      published: 5000
      target: 5000
    - protocol: udp
      published: 5000
      target: 5000
    - published: 9600
      target: 9600
    volumes:
    - /Library/WebServer/Documents/docker/docker-elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
    - /Library/WebServer/Documents/docker/docker-elk/logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
  setup:
    build:
      args:
        ELASTIC_VERSION: 8.0.0
      context: /Library/WebServer/Documents/docker/docker-elk/setup
    environment:
      ELASTIC_PASSWORD: changeme
      KIBANA_SYSTEM_PASSWORD: changeme
      LOGSTASH_INTERNAL_PASSWORD: changeme
    init: true
    networks:
      elk: null
    volumes:
    - setup:/state:Z
version: '3.7'
volumes:
  elasticsearch: {}
  setup: {}
```

```console
➜  docker-elk git:(main) docker-compose --version
docker-compose version 1.29.2, build 5becea4c
```
```console
➜  docker-elk git:(main) docker-compose --version
docker-compose version 1.29.2, build 5becea4c
```
```console
➜  docker-elk git:(main) docker-compose config
networks:
  elk:
    driver: bridge
services:
  elasticsearch:
    build:
      args:
        ELASTIC_VERSION: 8.0.0
      context: /Library/WebServer/Documents/docker/docker-elk/elasticsearch
    environment:
      ELASTIC_PASSWORD: changeme
      ES_JAVA_OPTS: -Xmx256m -Xms256m
      discovery.type: single-node
    networks:
      elk: null
    ports:
    - published: 9200
      target: 9200
    - published: 9300
      target: 9300
    volumes:
    - /Library/WebServer/Documents/docker/docker-elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
    - elasticsearch:/usr/share/elasticsearch/data:z
  kibana:
    build:
      args:
        ELASTIC_VERSION: 8.0.0
      context: /Library/WebServer/Documents/docker/docker-elk/kibana
    depends_on:
      elasticsearch:
        condition: service_started
    environment:
      KIBANA_SYSTEM_PASSWORD: changeme
    networks:
      elk: null
    ports:
    - published: 5601
      target: 5601
    volumes:
    - /Library/WebServer/Documents/docker/docker-elk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
  logstash:
    build:
      args:
        ELASTIC_VERSION: 8.0.0
      context: /Library/WebServer/Documents/docker/docker-elk/logstash
    depends_on:
      elasticsearch:
        condition: service_started
    environment:
      LOGSTASH_INTERNAL_PASSWORD: changeme
      LS_JAVA_OPTS: -Xmx256m -Xms256m
    networks:
      elk: null
    ports:
    - published: 5044
      target: 5044
    - protocol: tcp
      published: 5000
      target: 5000
    - protocol: udp
      published: 5000
      target: 5000
    - published: 9600
      target: 9600
    volumes:
    - /Library/WebServer/Documents/docker/docker-elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
    - /Library/WebServer/Documents/docker/docker-elk/logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
  setup:
    build:
      args:
        ELASTIC_VERSION: 8.0.0
      context: /Library/WebServer/Documents/docker/docker-elk/setup
    environment:
      ELASTIC_PASSWORD: changeme
      KIBANA_SYSTEM_PASSWORD: changeme
      LOGSTASH_INTERNAL_PASSWORD: changeme
    init: true
    networks:
      elk: null
    volumes:
    - setup:/state:Z
version: '3.7'
volumes:
  elasticsearch: {}
  setup: {}`
```

I am trying to login on http://localhost:9200/ with below curl command 
```console
➜  docker-elk git:(main) curl -D- http://localhost:9200 -u "elastic:changeme"`
HTTP/1.1 401 Unauthorized
WWW-Authenticate: Basic realm="security" charset="UTF-8"
WWW-Authenticate: ApiKey
content-type: application/json;charset=utf-8
content-length: 409

{"error":{"root_cause":[{"type":"security_exception","reason":"unable to authenticate user [elastic] for REST request [/]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","ApiKey"]}}],"type":"security_exception","reason":"unable to authenticate user [elastic] for REST request [/]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","ApiKey"]}},"status":401}%
```

If I access http://localhost:5601/ in the browser then I can see

**Kibana server is not ready yet.**
