### ISSUE TITLE
Pass .env values via Docker secrets

### ISSUE THREAD

**Issue by adouren** [deviantony/docker-elk#697]
Hello,

### Problem description

I put the passwords of an elastic stack in a ".env" file.

File .env:

ELASTIC_PASSWORD=elastic

…

elasticsearch:
image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
env_file:
- .env

…

When executing the stack, it works very well and the environment variables are updated in the stack. stack is ok.

Now when I put this ".env" file in secret docker the environment variables are not updated.

....
secrets:
elk_secret:
file: .env

services:
elasticsearch:
image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
secrets:
- elk_secret
....
Is there a trick to be able to put the ".env" file in docker secret and have the stack environment variables updated.

#### Docker setup

docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:14 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:24 2018
  OS/Arch:      linux/amd64
  Experimental: false

------ 

docker-compose version
docker-compose version 1.21.2, build a133471
docker-py version: 3.3.0
CPython version: 3.6.5
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

```
Best regard

Olivier

**Comment by antoineco** [comment]
@adouren Docker secrets are mounted as **file** under `/run/secrets`, not as environment variables.

To be able to consume those secret values as environment variables, you'd need to inject custom logic inside the container's `ENTRYPOINT` script to

1. Read the secret file
2. `export` the values it contains to environment variables to pass them to Elasticsearch

**Comment by adouren** [comment]
Thanks Antoineco, 

I was hoping there was an easier way than going through the entrypoint.

if possible, could you give me a simple example?

Deviantony's entreypoint.sh config is too complicated for me :(

**Comment by antoineco** [comment]
I believe the simplest way to do this is to override the entrypoint in the Compose file, run your logic, then shell out to Elasticsearch's original entrypoint.

Something along those lines (not tested, but should be very close to working):

```yaml
version: 3.7

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    # ...
    entrypoint:
    - /bin/tini
    - --
    - bash
    - -c
    - >
      eval /run/secrets/elk_secret;
      export ELASTIC_PASSWORD;
      exec /usr/local/bin/docker-entrypoint.sh;

  logstash:
  # ...
```
