### ISSUE TITLE
503 & Kibana server is not ready yet. How do I know that data are saved ?

### ISSUE THREAD

**Issue by lakonis** [deviantony/docker-elk#700]
### Problem description
I have updated ELK (following issue #645 ), but I encounter the following error when composing `sudo docker-compose -f docker-compose.yml up`:

```bash
[...]
elasticsearch_1  | {"type": "server", "timestamp": "2022-01-04T14:26:49,564Z", "level": "ERROR", "component": "o.e.x.s.a.f.SecurityActionFilter", "cluster.name": "docker-cluster", "node.name": "33907d556df4", "message": "blocking [cluster:monitor/stats] operation due to expired license. Cluster health, cluster stats and indices stats \noperations are blocked on license expiration. All data operations (read and write) continue to work. \nIf you have a new license, please update it. Otherwise, please reach out to your support contact.", "cluster.uuid": "xL2_bakbRs2A1XY0nMJpwQ", "node.id": "WIds4InyRJ2QzOGQ131Gwg"  }
elasticsearch_1  | {"type": "server", "timestamp": "2022-01-04T14:26:49,564Z", "level": "ERROR", "component": "o.e.x.m.c.c.ClusterStatsCollector", "cluster.name": "docker-cluster", "node.name": "33907d556df4", "message": "collector [cluster_stats] failed to collect data", "cluster.uuid": "xL2_bakbRs2A1XY0nMJpwQ", "node.id": "WIds4InyRJ2QzOGQ131Gwg" ,
elasticsearch_1  | "stacktrace": ["org.elasticsearch.ElasticsearchSecurityException: current license is non-compliant for [security]",
elasticsearch_1  | "at org.elasticsearch.license.LicenseUtils.newComplianceException(LicenseUtils.java:27) ~[?:?]",
elasticsearch_1  | "at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.apply(SecurityActionFilter.java:100) ~[?:?]",
elasticsearch_1  | "at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:177) ~[elasticsearch-7.16.1.jar:7.16.1]",
elasticsearch_1  | "at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:154) ~[elasticsearch-7.16.1.jar:7.16.1]",
elasticsearch_1  | "at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:82) ~[elasticsearch-7.16.1.jar:7.16.1]",
elasticsearch_1  | "at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:95) ~[elasticsearch-7.16.1.jar:7.16.1]",
elasticsearch_1  | "at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:73) ~[elasticsearch-7.16.1.jar:7.16.1]",
elasticsearch_1  | "at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:407) ~[elasticsearch-7.16.1.jar:7.16.1]",
elasticsearch_1  | "at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:392) ~[elasticsearch-7.16.1.jar:7.16.1]",
elasticsearch_1  | "at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:699) ~[elasticsearch-7.16.1.jar:7.16.1]",
elasticsearch_1  | "at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:34) ~[elasticsearch-7.16.1.jar:7.16.1]",
elasticsearch_1  | "at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:41) ~[elasticsearch-7.16.1.jar:7.16.1]",
elasticsearch_1  | "at org.elasticsearch.xpack.monitoring.collector.cluster.ClusterStatsCollector.doCollect(ClusterStatsCollector.java:90) ~[x-pack-monitoring-7.16.1.jar:7.16.1]",
elasticsearch_1  | "at org.elasticsearch.xpack.monitoring.collector.Collector.collect(Collector.java:95) [x-pack-monitoring-7.16.1.jar:7.16.1]",
elasticsearch_1  | "at org.elasticsearch.xpack.monitoring.MonitoringService$MonitoringExecution$1.doRun(MonitoringService.java:269) [x-pack-monitoring-7.16.1.jar:7.16.1]",
elasticsearch_1  | "at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-7.16.1.jar:7.16.1]",
elasticsearch_1  | "at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]",
elasticsearch_1  | "at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]",
elasticsearch_1  | "at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:718) [elasticsearch-7.16.1.jar:7.16.1]",
elasticsearch_1  | "at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]",
elasticsearch_1  | "at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]",
elasticsearch_1  | "at java.lang.Thread.run(Thread.java:833) [?:?]"] }
```
`sudo docker-compose -f docker-compose.yml up -d` gives:

```bash
Starting elasticsearchstack_elasticsearch_1 ... done
Starting elasticsearchstack_logstash_1      ... done
Starting elasticsearchstack_kibana_1        ... done
```
But from the browser I have a 503 error with the message `Kibana server is not ready yet`.

Looking at the running dockers `sudo docker ps --no-trunc`:

``` bash
CONTAINER ID                                                       IMAGE                              COMMAND                                                                                                                                                                   CREATED        STATUS         PORTS                                                                                            NAMES
d4a08293074b628765c3406de370c89c2adf500c52707fa65f762159fe0d28d5   elasticsearchstack_logstash        "/usr/local/bin/docker-entrypoint"                                                                                                                                        2 weeks ago    Up 4 minutes   0.0.0.0:5000->5000/tcp, 0.0.0.0:5044->5044/tcp, 0.0.0.0:9600->9600/tcp, 0.0.0.0:5000->5000/udp   elasticsearchstack_logstash_1
1ea99efb69e8e5e8b915f4e98d0a4def71cfe7bbafd00d4d0e1d5a4d1ef2c6ed   elasticsearchstack_kibana          "/bin/tini -- /usr/local/bin/kibana-docker"                                                                                                                               2 weeks ago    Up 4 minutes   0.0.0.0:5601->5601/tcp                                                                           elasticsearchstack_kibana_1
33907d556df43956afb223dc7c8e770c5ec3ccea0d4237f2784f91942c34388a   elasticsearchstack_elasticsearch   "/bin/tini -- /usr/local/bin/docker-entrypoint.sh eswrapper"                                                                                                              2 weeks ago    Up 4 minutes   0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp                                                   elasticsearchstack_elasticsearch_1
```

Before I go further, I would like to know whether the data are saved and available. 

#### Stack configuration

docker-stack.yaml

```yaml
more docker-stack.yml 
version: '3.3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    ports:
      - "9200:9200"
      - "9300:9300"
    configs:
      - source: elastic_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
      # Force publishing on the 'elk' overlay.
      network.publish_host: _eth0_
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1

  logstash:
    image: docker.elastic.co/logstash/logstash:7.13.4
    ports:
      - "5044:5044"
      - "5000:5000"
      - "9600:9600"
    configs:
      - source: logstash_config
        target: /usr/share/logstash/config/logstash.yml
      - source: logstash_pipeline
        target: /usr/share/logstash/pipeline/logstash.conf
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.4
    ports:
      - "5601:5601"
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1

configs:

  elastic_config:
    file: ./elasticsearch/config/elasticsearch.yml
  logstash_config:
    file: ./logstash/config/logstash.yml
  logstash_pipeline:
    file: ./logstash/pipeline/logstash.conf
  kibana_config:
    file: ./kibana/config/kibana.yml

networks:
  elk:
    driver: overlay
```

docker-compose.yml

```yaml
version: '3.2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx3048m -Xms3048m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
```

#### Docker setup

```console
$ docker version

Client: Docker Engine - Community
 Version:           20.10.9
 API version:       1.41
 Go version:        go1.16.8
 Git commit:        c2ea9bc
 Built:             Mon Oct  4 16:08:29 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
```

```console
$ docker-compose version

docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

```

#### Container logs

```console
$ docker-compose logs

Attaching to elasticsearchstack_logstash_1, elasticsearchstack_kibana_1, elasticsearchstack_elasticsearch_1
kibana_1         | {"type":"log","@timestamp":"2021-12-20T23:37:35+00:00","tags":["info","plugins-service"],"pid":8,"message":"Plugin \"metricsEntities\" is disabled."}
kibana_1         | {"type":"log","@timestamp":"2021-12-20T23:37:35+00:00","tags":["info","http","server","Preboot"],"pid":8,"message":"http server running at http://0.0.0.0:5601"}
kibana_1         | {"type":"log","@timestamp":"2021-12-20T23:37:35+00:00","tags":["warning","config","deprecation"],"pid":8,"message":"You should set server.basePath along with server.rewriteBasePath. Sta
rting in 7.0, Kibana will expect that all requests start with server.basePath rather than expecting you to rewrite the requests in your reverse proxy. Set server.rewriteBasePath to false to preserve the current 
behavior and silence this warning."}
kibana_1         | {"type":"log","@timestamp":"2021-12-20T23:37:35+00:00","tags":["warning","config","deprecation"],"pid":8,"message":"Starting in 8.0, the Kibana logging format will be changing. This may
 affect you if you are doing any special handling of your Kibana logs, such as ingesting logs into Elasticsearch for further analysis. If you are using the new logging configuration, you are already receiving lo
gs in both old and new formats, and the old format will simply be going away. If you are not yet using the new logging configuration, the log format will change upon upgrade to 8.0. Beginning in 8.0, the format 
of JSON logs will be ECS-compatible JSON, and the default pattern log format will be configurable with our new logging system. Please refer to the documentation for more information about the new logging format.
"}
kibana_1         | {"type":"log","@timestamp":"2021-12-20T23:37:35+00:00","tags":["warning","config","deprecation"],"pid":8,"message":"Kibana is configured to authenticate to Elasticsearch with the \"elas
tic\" user. Use a service account token instead."}
kibana_1         | {"type":"log","@timestamp":"2021-12-20T23:37:35+00:00","tags":["warning","config","deprecation"],"pid":8,"message":"Use Kibana application privileges to grant reporting privileges. Usin
g  \"xpack.reporting.roles.allow\" to grant reporting privileges is deprecated. The \"xpack.reporting.roles.enabled\" setting will default to false in a future release."}
kibana_1         | {"type":"log","@timestamp":"2021-12-20T23:37:35+00:00","tags":["warning","config","deprecation"],"pid":8,"message":"User sessions will automatically time out after 8 hours of inactivity
 starting in 8.0. Override this value to change the timeout."}
kibana_1         | {"type":"log","@timestamp":"2021-12-20T23:37:35+00:00","tags":["warning","config","deprecation"],"pid":8,"message":"Users are automatically required to log in again after 30 days starti
ng in 8.0. Override this value to change the timeout."}
kibana_1         | {"type":"log","@timestamp":"2021-12-20T23:37:35+00:00","tags":["info","plugins-system","standard"],"pid":8,"message":"Setting up [113] plugins: [translations,licensing,globalSearch,glob
alSearchProviders,features,licenseApiGuard,code,usageCollection,xpackLegacy,taskManager,telemetryCollectionManager,telemetryCollectionXpack,kibanaUsageCollection,share,embeddable,uiActionsEnhanced,screenshotMode
,banners,telemetry,newsfeed,mapsEms,mapsLegacy,kibanaLegacy,fieldFormats,expressions,dataViews,charts,esUiShared,bfetch,data,savedObjects,presentationUtil,expressionShape,expressionRevealImage,expressionRepeatIm
age,expressionMetric,expressionImage,customIntegrations,home,searchprofiler,painlessLab,grokdebugger,management,watcher,licenseManagement,advancedSettings,spaces,security,savedObjectsTagging,reporting,canvas,lis
ts,ingestPipelines,fileUpload,encryptedSavedObjects,dataEnhanced,cloud,snapshotRestore,eventLog,actions,alerting,triggersActionsUi,transform,stackAlerts,ruleRegistry,visualizations,visTypeXy,visTypeVislib,visTyp
eVega,visTypeTimelion,visTypeTagcloud,visTypeTable,visTypePie,visTypeMetric,visTypeMarkdown,tileMap,regionMap,expressionTagcloud,expressionMetricVis,console,graph,fleet,indexManagement,remoteClusters,crossCluste
rReplication,indexLifecycleManagement,dashboard,maps,dashboardMode,dashboardEnhanced,visualize,visTypeTimeseries,rollup,indexPatternFieldEditor,lens,cases,timelines,discover,osquery,observability,discoverEnhance
d,dataVisualizer,ml,uptime,securitySolution,infra,upgradeAssistant,monitoring,logstash,enterpriseSearch,apm,savedObjectsManagement,indexPatternManagement]"}
kibana_1         | {"type":"log","@timestamp":"2021-12-20T23:37:35+00:00","tags":["info","plugins","taskManager"],"pid":8,"message":"TaskManager is identified by the Kibana UUID: d94546ff-f3c8-48ec-abdc-c
6a23c9b72d6"}
kibana_1         | {"type":"log","@timestamp":"2021-12-20T23:37:36+00:00","tags":["warning","plugins","security","config"],"pid":8,"message":"Generating a random key for xpack.security.encryptionKey. To p
revent sessions from being invalidated on restart, please set xpack.security.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command."}
kibana_1         | {"type":"log","@timestamp":"2021-12-20T23:37:36+00:00","tags":["warning","plugins","security","config"],"pid":8,"message":"Session cookies will be transmitted over insecure connections.
 This is not recommended."}
kibana_1         | {"type":"log","@timestamp":"2021-12-20T23:37:36+00:00","tags":["warning","plugins","security","config"],"pid":8,"message":"Generating a random key for xpack.security.encryptionKey. To p
revent sessions from being invalidated on restart, please set xpack.security.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command."}
kibana_1         | {"type":"log","@timestamp":"2021-12-20T23:37:36+00:00","tags":["warning","plugins","security","config"],"pid":8,"message":"Session cookies will be transmitted over insecure connections.
 This is not recommended."}
kibana_1         | {"type":"log","@timestamp":"2021-12-20T23:37:36+00:00","tags":["warning","plugins","reporting","config"],"pid":8,"message":"Generating a random key for xpack.reporting.encryptionKey. To
 prevent sessions from being invalidated on restart, please set xpack.reporting.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command."}
kibana_1         | {"type":"log","@timestamp":"2021-12-20T23:37:36+00:00","tags":["warning","plugins","encryptedSavedObjects"],"pid":8,"message":"Saved objects encryption key is not set. This will severel
y limit Kibana functionality. Please set xpack.encryptedSavedObjects.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command."}
kibana_1         | {"type":"log","@timestamp":"2021-12-20T23:37:36+00:00","tags":["warning","plugins","actions"],"pid":8,"message":"APIs are disabled because the Encrypted Saved Objects plugin is missing 
encryption key. Please set xpack.encryptedSavedObjects.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command."}
kibana_1         | {"type":"log","@timestamp":"2021-12-20T23:37:36+00:00","tags":["warning","plugins","alerting"],"pid":8,"message":"APIs are disabled because the Encrypted Saved Objects plugin is missing
 encryption key. Please set xpack.encryptedSavedObjects.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command."}
kibana_1         | {"type":"log","@timestamp":"2021-12-20T23:37:36+00:00","tags":["info","plugins","ruleRegistry"],"pid":8,"message":"Installing common resources shared between all indices"}
kibana_1         | {"type":"log","@timestamp":"2021-12-20T23:37:37+00:00","tags":["warning","plugins","reporting","config"],"pid":8,"message":"Chromium sandbox provides an additional layer of protection, 
but is not supported for Linux CentOS 8.5.2111\n OS. Automatically setting 'xpack.reporting.capture.browser.chromium.disableSandbox: true'."}
logstash_1       | Using bundled JDK: /usr/share/logstash/jdk
logstash_1       | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
logstash_1       | Sending Logstash logs to /usr/share/logstash/logs which is now configured via log4j2.properties
logstash_1       | [2021-12-20T23:37:50,441][INFO ][logstash.runner          ] Log4j configuration path used is: /usr/share/logstash/config/log4j2.properties
logstash_1       | [2021-12-20T23:37:50,452][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.16.1", "jruby.version"=>"jruby 9.2.20.1 (2.5.8) 2021-11-30 2a2962fbd1 OpenJDK 64-Bi
t Server VM 11.0.13+8 on 11.0.13+8 +indy +jit [linux-x86_64]"}

```
