### ISSUE TITLE
Add elasticsearch container as a cluster?

### ISSUE THREAD

**Issue by WeiWeiWesley** [deviantony/docker-elk#75]
hello~
## here is my docker-compose.yml

``` yml
elasticsearch:
    image: elasticsearch:latest
    command: elasticsearch -Des.node.name="es1" -Des.cluster.name="mycluster" -Des.network.host=_eth0_ -Des.network.publish_host=192.168.153.40 -Des.discovery.zen.ping.unicast.hosts=192.168.153.40:9200,192.168.153.40:9400 -Des.discovery.zen.minimum_master_nodes=1
    ports:
    - "9200:9200"
    - "9300:9300"


logstash:
  build: logstash/
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
  ports:
    - "5000:5000"
    - "5001:5001" 
  links:
    - elasticsearch

kibana:
  build: kibana/
  volumes:
    - ./kibana/config/:/opt/kibana/config/
  ports:
    - "5601:5601"
  links:
    - elasticsearch
```
