### ISSUE TITLE
Config file location for kibana

### ISSUE THREAD

**Issue by ansrivas** [deviantony/docker-elk#80]
Hi thanks for this wonderful project. 
I have a small confusion w.r.t the config file for Kibana. 

Renaming the name of `elasticsearch` container makes it unreachable to Kibana since the correct config is not being read.

```
kibana_1  | {"type":"log","@timestamp":"2016-11-28T14:04:53Z","tags":["warning","elasticsearch"],"pid":11,"message":"Unable to revive connection: http://elasticsearch:9200/"}
```

The default config is read from `/etc/kibana/kibana.yml` as mentioned [here](https://github.com/docker-library/kibana/blob/master/5.0/docker-entrypoint.sh#L12). 

But for eg. if I change the name of `elasticsearch` container I need to copy the config to `/etc/kibana/` rather than `./kibana/config/:/opt/kibana/config/`  as mentioned in default compose file  `https://github.com/deviantony/docker-elk/blob/master/docker-compose.yml#L27`.  

Replacement could be something like this:
 ```bash
    volumes:
      - ./kibana/config/:/etc/kibana/
```

Issue can be reproduced by using following `docker-compose.yml`
1. Change the names of elasticsearch in `kibana.yml` to `elasticsearch.url: "http://elasticsearch-url:9200"`
2. Change the name in `logstash.conf` : `hosts => "elasticsearch-url:9200"`

```
version: '2'

services:
  elasticsearch-url:
    build: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    networks:
      - docker_elk
  logstash:
    build: logstash/
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch-url
  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    ports:
      - "5601:5601"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch-url

networks:
  docker_elk:
    driver: bridge
```
