### ISSUE TITLE
Implement Docker-Compose Health Checks

### ISSUE THREAD

**Issue by nikhilbadyal** [deviantony/docker-elk#804]
Docker(compose TBS) provides [health checks](https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck). I think we should add health for all the services. 
This will ensure that container are not just running but actually healthy and able to serve requests.
This might help in some other places too like [this won't be needed](https://github.com/deviantony/docker-elk/blob/main/setup/helpers.sh#L24). 

Example - 
If we add a health check on `ES` container. `setup` container will only start if ElasticSeach Container is healthy.

```
  elasticsearch:
    ...
    healthcheck:
      test: [ "CMD", "sh", "-c", "curl -sfk https://elastic:$ELASTIC_PASSWORD@host.docker.internal:9200/_cat/health || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 10
```

and then in setup we can do
```
  setup:
    ...
    depends_on:
      elasticsearch:
        condition: service_healthy
```

This will make sure setup start only when `_cat/health` works(doesn't fail)
