### ISSUE TITLE
Failed to connect to logstash from filebeat

### ISSUE THREAD

**Issue by sovannarithcheav** [deviantony/docker-elk#808]
Hello,
I'm trying to configure filebeat.yml to output to logstash instance, but seem like it can not connect to each other.

`filebeat.yml`
```yml
output.logstash:
    hosts: [ http://logstash:5044 ]
    username: beats_system
    password: ${BEATS_SYSTEM_PASSWORD}
```

`filebeat` Logs:
```log
2022-12-21 13:49:40 {"log.level":"error","@timestamp":"2022-12-21T06:49:40.571Z","log.logger":"publisher_pipeline_output","log.origin":{"file.name":"pipeline/client_worker.go","file.line":150},"message":"Failed to connect to backoff(async(tcp://[http://logstash:5044]:5044)): lookup http://logstash:5044: no such host","service.name":"filebeat","ecs.version":"1.6.0"}
```
What should I do?
