### ISSUE TITLE
elastic-agent fleet installation Fleet Server - Error - x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by jkeruzec** [deviantony/docker-elk#830]
### Problem description

I currently installed docker-elk TLS branch from fresh install
I'm running the TLS version of docker-elk with all certificates from "certs" directory". Kibana is starting well with Elastic search.

I wanted to add an elastic agent to fleet server

I have this line but error on certificate
```
{"log.level":"error","@timestamp":"2023-02-20T13:56:10.449Z","message":"Failed to connect to backoff(elasticsearch(https://elasticsearch:9200)): Get \"https://elasticsearch:9200\": x509: certificate signed by unknown authority","component":{"binary":"metricbeat","dataset":"elastic_agent.metricbeat","id":"system/metrics-default","type":"system/metrics"},"log":{"source":"system/metrics-default"},"log.logger":"publisher_pipeline_output","log.origin":{"file.line":150,"file.name":"pipeline/client_worker.go"},"service.name":"metricbeat","ecs.version":"1.6.0","ecs.version":"1.6.0"}
```

My compose file
```
stage-elastic-agent-elk:
    image: docker.elastic.co/beats/elastic-agent:8.6.2
    container_name: fleet-server
    user: root
    volumes:
      - /software/nginx/log/:/var/nginx/log/:ro
      - /software/compose/docker-elk/tls/certs/:/certs/:ro
    ports:
      - 8220:8220
    environment:
      - FLEET_SERVER_ENABLE=true
      - FLEET_SERVER_ELASTICSEARCH_HOST=https://elasticsearch:9200
      - FLEET_ENROLL=1
      - FLEET_URL=https://fleet-server:8220
      - FLEET_SERVER_SERVICE_TOKEN=AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE2NzY4OTgwOTc5NzE6LVJIR1BrYjFUMnlrQ0ZQYTNJbC1lQQ
      - FLEET_SERVER_POLICY_ID=fleet-server-policy
      - FLEET_SERVER_CERT_KEY=/certs/fleet-server/fleet-server.key
      - FLEET_SERVER_CERT=/certs/fleet-server/fleet-server.crt
      - ELASTICSEARCH_CA=/certs/elasticsearch/elasticsearch.crt
      - FLEET_SERVER_ELASTICSEARCH_CA_TRUSTED_FINGERPRINT=846637d1bb82209640d31b79869a370c8e47c2dc15c7eafd4f3d615e51e3d503
    networks:
      - elk
```

I almost tried every possible combination for ELASTICSEARCH_CA and even the undocumented FLEET_SERVER_ELASTICSEARCH_CA_TRUSTED_FINGERPRINT ...

It seems that running a full secure ELK stack is very complicated, can you help ?
