### ISSUE TITLE
Problem Kibana server is not ready yet

### ISSUE THREAD

**Issue by adouren** [deviantony/docker-elk#855]
Hi,

Problem description : 

All stacks are running but Kibana remains Kibana server is not ready yet

Docker-stack.yml
```yaml
version: '3.6'

volumes:
  elastic-data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.21.2.220,rw,nfsvers=4
      device: ":/data/docker-nfs/elkstk/elastic-data"
  kibana-data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.21.2.220,rw,nfsvers=4
      device: ":/data/docker-nfs/elkstk/kibana-data"
  logs_enquetes:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.21.2.220,rw,nfsvers=4
      device: ":/data/docker-nfs/elkstk/logs/enquetes"
 # 
# secrets:
#  elk_secret:
#    file: environment

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    # image: docker.elastic.co/elasticsearch/elasticsearch:8.1.0
    env_file:
      - .env
    # secrets:
    #  - source: elk_secret
    #    target: /etc/environment

    # secrets:
    #  - elk_secret
    ports:
      - "6892:9200"
      - "6893:9300"
    configs:
      - source: elkstk_elastic_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    volumes:
      - type: volume
        source: elastic-data
        target: /usr/share/elasticsearch/data
        read_only: false
        volume:
          driver: nfs
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      # ELASTIC_PASSWORD: elastic
      # ELASTIC_PASSWORD: $ELASTIC_PASSWORD
      # xpack.security.enabled: $ELASTIC_SECURITY
      #  Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
      # Force publishing on the 'elk' overlay.
      network.publish_host: _eth0_
    networks:
      - elkstk_elk
    deploy:
      mode: replicated
      replicas: 1

  logstash:
    image: docker.elastic.co/logstash/logstash:7.16.3
    # image: docker.elastic.co/logstash/logstash:8.1.0
    # IL FAUT BIEN DECLARER env_file ICI
    env_file:
      - .env
    # secrets:
    #  - elk_secret
    ports:
      - "6844:5044"
      - "6845:5045"
      - "6850:5000"
      - "6896:9600"
    configs:
      - source: elkstk_logstash_config
        target: /usr/share/logstash/config/logstash.yml
      - source: elkstk_logstash_asj-dev_pipeline
        target: /usr/share/logstash/pipeline/logstash_asj-dev.conf
      - source: elkstk_logstash_espaces-rencontre-dev_pipeline
        target: /usr/share/logstash/pipeline/logstash_espaces-rencontre-dev.conf
    # volumes:
    #   - /var/lib/docker/volumes/asj-dev_logs/_data:/usr/share/logs:rw
    volumes:
      - type: volume
        source: logs_enquetes
        target: /usr/share/logs
        read_only: false
        volume:
          driver: nfs
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elkstk_elk
    depends_on:
      - elasticsearch
    deploy:
      mode: replicated
      replicas: 1

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.3
    # image: docker.elastic.co/kibana/kibana:8.1.0
    # IL FAUT BIEN DECLARER env_file ICI
    env_file:
      - .env
    # secrets:
    #  - elk_secret
    ports:
      - "6856:5601"
    configs:
      - source: elkstk_kibana_config
        target: /usr/share/kibana/config/kibana.yml
    volumes:
      - type: volume
        source: kibana-data
        target: /usr/share/kibana/data
        read_only: false
        volume:
          driver: nfs
    networks:
      - elkstk_elk
    depends_on:
      - elasticsearch
    deploy:
      mode: replicated
      replicas: 1

  filebeat_espaces-rencontre-dev:
    image: docker.elastic.co/beats/filebeat:7.16.3
    # image: docker.elastic.co/beats/filebeat:8.1.0
    user: root
    configs:
      - source: elkstk_filebeat_espaces-rencontre-dev_config
        target: /usr/share/filebeat/filebeat.yml
      - source: elkstk_filebeat_modules_espaces-rencontre-dev_config
        target: /usr/share/filebeat/modules.d/enquetes_espaces-rencontre-dev.yml
    volumes:
      - type: volume
        source: logs_enquetes
        target: /usr/share/filebeat/logs/enquetes 
        read_only: false
        volume:
          nocopy: true
          driver: nfs
    networks:
      - elkstk_elk
    depends_on:
      - logstash
    deploy:
      mode: replicated
      replicas: 1

  filebeat_asj-dev:
    image: docker.elastic.co/beats/filebeat:7.16.3
    # image: docker.elastic.co/beats/filebeat:8.1.0
    user: root
    configs:
      - source: elkstk_filebeat_asj-dev_config
        target: /usr/share/filebeat/filebeat.yml
      - source: elkstk_filebeat_modules_asj-dev_config
        target: /usr/share/filebeat/modules.d/enquetes_asj-dev.yml
    volumes:
      - type: volume
        source: logs_enquetes
        target: /usr/share/filebeat/logs/enquetes 
        read_only: false
        volume:
          nocopy: true
          driver: nfs
    networks:
      - elkstk_elk
    depends_on:
      - logstash
    deploy:
      mode: replicated
      replicas: 1

configs:
   elkstk_elastic_config:
    file: ./config/elkstk_elastic_config
   elkstk_logstash_config:
    file: ./config/elkstk_logstash_config
   elkstk_logstash_asj-dev_pipeline:
    file: ./config/elkstk_logstash_asj-dev_pipeline
   elkstk_logstash_espaces-rencontre-dev_pipeline:
    file: ./config/elkstk_logstash_espaces-rencontre-dev_pipeline
   elkstk_kibana_config:
    file: ./config/elkstk_kibana_config
   elkstk_filebeat_asj-dev_config:
    file: ./config/elkstk_filebeat_asj-dev_config 
   elkstk_filebeat_modules_asj-dev_config:
    file: ./config/elkstk_filebeat_modules_asj-dev_config
   elkstk_filebeat_espaces-rencontre-dev_config:
    file: ./config/elkstk_filebeat_espaces-rencontre-dev_config
   elkstk_filebeat_modules_espaces-rencontre-dev_config:
    file: ./config/elkstk_filebeat_modules_espaces-rencontre-dev_config
    
networks:
  elkstk_elk:
    driver: overlay
```	
	
elkstk_kibana_config
```yaml
## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/master/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.ts
#
server.name: kibana
server.host: 0.0.0.0
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
monitoring.ui.container.elasticsearch.enabled: true

## X-Pack security credentials
#
# LA DECLARATION DE ${ELASTIC_PASSWORD} FONCTIONNE. Plus très sur
# elasticsearch.password: $ELASTIC_PASSWORD
# elasticsearch.password: elastic
# elasticsearch.username: elastic
elasticsearch.password: elastic
```
.env
```
ELASTIC_PASSWORD=elastic
```
Container Logs Kibana : 
```
Plugin "metricsEntities" is disabled. | type=log @timestamp=2023-04-28T13:25:49+00:00 tags=["info","plugins-service"] pid=7
http server running at http://0.0.0.0:5601 | type=log @timestamp=2023-04-28T13:25:49+00:00 tags=["info","http","server","Preboot"] pid=7
Starting in 8.0, the Kibana logging format will be changing. This may affect you if you are doing any special handling of your Kibana logs, such as ingesting logs into Elasticsearch for further analysis. If you are using the new logging configuration, you are already receiving logs in both old and new formats, and the old format will simply be going away. If you are not yet using the new logging configuration, the log format will change upon upgrade to 8.0. Beginning in 8.0, the format of JSON logs will be ECS-compatible JSON, and the default pattern log format will be configurable with our new logging system. Please refer to the documentation for more information about the new logging format. | type=log @timestamp=2023-04-28T13:25:50+00:00 tags=["warning","config","deprecation"] pid=7
Use Kibana application privileges to grant reporting privileges. Using  "xpack.reporting.roles.allow" to grant reporting privileges is deprecated. The "xpack.reporting.roles.enabled" setting will default to false in a future release. | type=log @timestamp=2023-04-28T13:25:50+00:00 tags=["warning","config","deprecation"] pid=7
User sessions will automatically time out after 8 hours of inactivity starting in 8.0. Override this value to change the timeout. | type=log @timestamp=2023-04-28T13:25:50+00:00 tags=["warning","config","deprecation"] pid=7
Users are automatically required to log in again after 30 days starting in 8.0. Override this value to change the timeout. | type=log @timestamp=2023-04-28T13:25:50+00:00 tags=["warning","config","deprecation"] pid=7
Setting up [113] plugins: [translations,licensing,globalSearch,globalSearchProviders,features,licenseApiGuard,code,usageCollection,xpackLegacy,taskManager,telemetryCollectionManager,telemetryCollectionXpack,kibanaUsageCollection,share,embeddable,uiActionsEnhanced,screenshotMode,banners,telemetry,newsfeed,mapsEms,mapsLegacy,kibanaLegacy,fieldFormats,expressions,dataViews,charts,esUiShared,bfetch,data,savedObjects,presentationUtil,expressionShape,expressionRevealImage,expressionRepeatImage,expressionMetric,expressionImage,customIntegrations,home,searchprofiler,painlessLab,grokdebugger,management,watcher,licenseManagement,advancedSettings,spaces,security,savedObjectsTagging,reporting,canvas,lists,ingestPipelines,fileUpload,encryptedSavedObjects,dataEnhanced,cloud,snapshotRestore,eventLog,actions,alerting,triggersActionsUi,transform,stackAlerts,ruleRegistry,visualizations,visTypeXy,visTypeVislib,visTypeVega,visTypeTimelion,visTypeTagcloud,visTypeTable,visTypePie,visTypeMetric,visTypeMarkdown,tileMap,regionMap,expressionTagcloud,expressionMetricVis,console,graph,fleet,indexManagement,remoteClusters,crossClusterReplication,indexLifecycleManagement,dashboard,maps,dashboardMode,dashboardEnhanced,visualize,visTypeTimeseries,rollup,indexPatternFieldEditor,lens,cases,timelines,discover,osquery,observability,discoverEnhanced,dataVisualizer,ml,uptime,securitySolution,infra,upgradeAssistant,monitoring,logstash,enterpriseSearch,apm,savedObjectsManagement,indexPatternManagement] | type=log @timestamp=2023-04-28T13:25:50+00:00 tags=["info","plugins-system","standard"] pid=7
TaskManager is identified by the Kibana UUID: 6ae0e2c0-6e72-46ee-9918-c6b12de6ad96 | type=log @timestamp=2023-04-28T13:25:50+00:00 tags=["info","plugins","taskManager"] pid=7
Generating a random key for xpack.security.encryptionKey. To prevent sessions from being invalidated on restart, please set xpack.security.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command. | type=log @timestamp=2023-04-28T13:25:50+00:00 tags=["warning","plugins","security","config"] pid=7
Session cookies will be transmitted over insecure connections. This is not recommended. | type=log @timestamp=2023-04-28T13:25:50+00:00 tags=["warning","plugins","security","config"] pid=7
Generating a random key for xpack.security.encryptionKey. To prevent sessions from being invalidated on restart, please set xpack.security.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command. | type=log @timestamp=2023-04-28T13:25:50+00:00 tags=["warning","plugins","security","config"] pid=7
Session cookies will be transmitted over insecure connections. This is not recommended. | type=log @timestamp=2023-04-28T13:25:50+00:00 tags=["warning","plugins","security","config"] pid=7
Generating a random key for xpack.reporting.encryptionKey. To prevent sessions from being invalidated on restart, please set xpack.reporting.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command. | type=log @timestamp=2023-04-28T13:25:50+00:00 tags=["warning","plugins","reporting","config"] pid=7
Saved objects encryption key is not set. This will severely limit Kibana functionality. Please set xpack.encryptedSavedObjects.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command. | type=log @timestamp=2023-04-28T13:25:50+00:00 tags=["warning","plugins","encryptedSavedObjects"] pid=7
APIs are disabled because the Encrypted Saved Objects plugin is missing encryption key. Please set xpack.encryptedSavedObjects.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command. | type=log @timestamp=2023-04-28T13:25:50+00:00 tags=["warning","plugins","actions"] pid=7
APIs are disabled because the Encrypted Saved Objects plugin is missing encryption key. Please set xpack.encryptedSavedObjects.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command. | type=log @timestamp=2023-04-28T13:25:50+00:00 tags=["warning","plugins","alerting"] pid=7
Installing common resources shared between all indices | type=log @timestamp=2023-04-28T13:25:50+00:00 tags=["info","plugins","ruleRegistry"] pid=7
Chromium sandbox provides an additional layer of protection, but is not supported for Linux CentOS 8.5.2111
 OS. Automatically setting 'xpack.reporting.capture.browser.chromium.disableSandbox: true'. | type=log @timestamp=2023-04-28T13:25:51+00:00 tags=["warning","plugins","reporting","config"] pid=7
Error [ProductNotSupportedSecurityError]: The client is unable to verify that the server is Elasticsearch due to security privileges on the server side. Some functionality may not be compatible if the server is running an unsupported product.
    at /usr/share/kibana/node_modules/@elastic/elasticsearch/lib/Transport.js:576:19
    at onBody (/usr/share/kibana/node_modules/@elastic/elasticsearch/lib/Transport.js:369:9)
    at IncomingMessage.onEnd (/usr/share/kibana/node_modules/@elastic/elasticsearch/lib/Transport.js:291:11)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) | type=log @timestamp=2023-04-28T13:25:51+00:00 tags=["warning","process"] pid=7
Unable to retrieve version information from Elasticsearch nodes. security_exception: [security_exception] Reason: missing authentication credentials for REST request [/_nodes?filter_path=nodes.*.version%2Cnodes.*.http.publish_address%2Cnodes.*.ip] | type=log @timestamp=2023-04-28T13:25:53+00:00 tags=["error","elasticsearch-service"] pid=7
Error: Timeout: it took more than 1200000ms
    at Timeout._onTimeout (/usr/share/kibana/x-pack/plugins/rule_registry/server/rule_data_plugin_service/resource_installer.js:54:20)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) | type=log @timestamp=2023-04-28T13:45:50+00:00 tags=["error","plugins","ruleRegistry"] pid=7
Error: Failure installing common resources shared between all indices. Timeout: it took more than 1200000ms
    at ResourceInstaller.installWithTimeout (/usr/share/kibana/x-pack/plugins/rule_registry/server/rule_data_plugin_service/resource_installer.js:63:13)
    at ResourceInstaller.installCommonResources (/usr/share/kibana/x-pack/plugins/rule_registry/server/rule_data_plugin_service/resource_installer.js:77:5) | type=log @timestamp=2023-04-28T13:45:50+00:00 tags=["error","plugins","ruleRegistry"] pid=7
```

DOCKER VERSION
```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
```
Best regard

Olivier
