### ISSUE TITLE
Push Filebeat dashboards to Kibana error

### ISSUE THREAD

**Issue by grizzlycode** [deviantony/docker-elk#862]
### Problem description

I have two docker instances one with this ELK stack and another with Filebeat docker container. I'm sending remote Filebeat data successfully via SSL to Elasticsearch. I have configured the "Kibana setup" options in Filebeat config however, I'm unable to successfully load dashboards to Kibana. 

I get the following error:

> Loading dashboards (Kibana must be running and reachable)
Exiting: error connecting to Kibana: fail to get the Kibana version: HTTP GET request to https://1.2.3.4:5601/api/status fails: fail to execute the HTTP GET request: Get "https://1.2.3.4:5601/api/status": dial tcp 1.2.3.4:5601: connect: connection refused (status=0). Response:

#### Stack configuration

Filebeat Config:

```
filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

setup.kibana:
  host: "https://1.2.3.4:5601" 
  ssl.enabled: true
  ssl.certificate_authorities: /certs/ca.crt

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
- add_docker_metadata: ~

output.elasticsearch:
  hosts: https://1.2.3.4:9200
  username: elastic                    
  password: <password>     
  ssl.certificate_authorities: /certs/ca.crt

```

I tried with and without SSL in Filebeat config and it won't work. Have I made an error in my Filebeat config? Is there some additional configuration required somewhere else?

**Comment by antoineco** [comment]
`1.2.3.4:5601: connect: connection refused` indicates that something, probably a firewall, is blocking ingress traffic to port 5601.

**Comment by grizzlycode** [comment]
Both VMs are on the same network and I can use the kibana web interface. My network firewall isn't configured to block activity to this port. 

On my test VMs I currently have INPUT chain set to "accept" it shouldn't be blocking anything. 

iptables:
> Chain INPUT (policy ACCEPT 0 packets, 0 bytes)

Its weird that I can netcat successfully to all the open ports on the elasticsearch stack, but 5601. 

Seeing as how my newtork firewall and host iptables aren't set to block this activity  is why I was asking if there is a config issue that I might be missing somewhere?

**Comment by grizzlycode** [comment]
Ok just to test it I swtiched off Traefik and exposed 5601 and I can push it, but I had to drop the https on address to make it work. 

```
setup.kibana:
  host: "http://1.2.3.4:5601" 
  ssl.enabled: true
  ssl.certificate_authorities: /certs/ca.crt
```

I don't suppose you know how to get it to push through Traefik? If not, I'll figure it out later, the containers work as designed if not proxied. You can close case if you are unfamiliar with Traefik.
