### ISSUE TITLE
share network

### ISSUE THREAD

**Issue by murilolivorato** [deviantony/docker-elk#888]
hello , I am using docker-elk .
very nice , thanks for share this code with uss.

well , I am trying to share this network ( docker-compose ) . and access from other network ( other docker compose )

but I was not success .
it is that posible to I aceess from other docker compose ?
the elk network

**Comment by antoineco** [comment]
1. It's possible to connect containers to multiple networks using [`docker network connect`](https://docs.docker.com/engine/reference/commandline/network_connect/).

1. Another option is to start the external applications [inside a pre-existing network](https://docs.docker.com/compose/networking/#use-a-pre-existing-network):

    ```yaml
    # docker-compose.yml

    services:
      myapp:
        image: nginx:alpine
        networks:
          - elk

    networks:
      elk:
        external:
          name: dockerelk_elk
    ```
